# Fase 0 - Ingesta de datos

In [1]:
import os
import urllib

In [2]:
if not os.path.exists("data"):
    os.makedirs("data")

## Descargar Datasets Abiertos

source: https://developer.imdb.com/non-commercial-datasets/

In [3]:
urllib.request.urlretrieve(
    "https://datasets.imdbws.com/title.basics.tsv.gz", 
    "data/title.basics.tsv.gz"
)
urllib.request.urlretrieve(
    "https://datasets.imdbws.com/title.ratings.tsv.gz", 
    "data/title.ratings.tsv.gz"
)

('data/title.ratings.tsv.gz', <http.client.HTTPMessage at 0xffff993fcb30>)

In [12]:
# !uv add polars

Resolved 3 packages in 1ms
Checked 2 packages in 0.67ms

In [6]:
import polars as pl
pl.__version__

'1.42.1'

### Basics Data

In [8]:
basics_df = pl.read_csv(
    "data/title.basics.tsv.gz",
    separator="\t",
    null_values="\\N", # to handle missing values
    quote_char=None,   # to avoid issues with quotes in the data
)

In [9]:
basics_df.head()

shape: (5, 9)
┌───────────┬───────────┬────────────┬───────────┬───┬───────────┬─────────┬───────────┬───────────┐
│ tconst    ┆ titleType ┆ primaryTit ┆ originalT ┆ … ┆ startYear ┆ endYear ┆ runtimeMi ┆ genres    │
│ ---       ┆ ---       ┆ le         ┆ itle      ┆   ┆ ---       ┆ ---     ┆ nutes     ┆ ---       │
│ str       ┆ str       ┆ ---        ┆ ---       ┆   ┆ i64       ┆ str     ┆ ---       ┆ str       │
│           ┆           ┆ str        ┆ str       ┆   ┆           ┆         ┆ i64       ┆           │
╞═══════════╪═══════════╪════════════╪═══════════╪═══╪═══════════╪═════════╪═══════════╪═══════════╡
│ tt0000001 ┆ short     ┆ Carmencita ┆ Carmencit ┆ … ┆ 1894      ┆ null    ┆ 1         ┆ Documenta │
│           ┆           ┆            ┆ a         ┆   ┆           ┆         ┆           ┆ ry,Short  │
│ tt0000002 ┆ short     ┆ Le clown   ┆ Le clown  ┆ … ┆ 1892      ┆ null    ┆ 5         ┆ Animation │
│           ┆           ┆ et ses     ┆ et ses    ┆   ┆           ┆         ┆           ┆ ,Short    │
│           ┆           ┆ chiens     ┆ chiens    ┆   ┆           ┆         ┆           ┆           │
│ tt0000003 ┆ short     ┆ Poor       ┆ Pauvre    ┆ … ┆ 1892      ┆ null    ┆ 5         ┆ Animation │
│           ┆           ┆ Pierrot    ┆ Pierrot   ┆   ┆           ┆         ┆           ┆ ,Comedy,R │
│           ┆           ┆            ┆           ┆   ┆           ┆         ┆           ┆ omance    │
│ tt0000004 ┆ short     ┆ Un bon     ┆ Un bon    ┆ … ┆ 1892      ┆ null    ┆ 12        ┆ Animation │
│           ┆           ┆ bock       ┆ bock      ┆   ┆           ┆         ┆           ┆ ,Short    │
│ tt0000005 ┆ short     ┆ Blacksmith ┆ Blacksmit ┆ … ┆ 1893      ┆ null    ┆ 1         ┆ Short     │
│           ┆           ┆ Scene      ┆ h Scene   ┆   ┆           ┆         ┆           ┆           │
└───────────┴───────────┴────────────┴───────────┴───┴───────────┴─────────┴───────────┴───────────┘

In [10]:
# how many rows and columns are in the dataframe
basics_df.shape

(12633670, 9)

### Ratings Data

In [11]:
ratings_df = pl.read_csv(
    "data/title.ratings.tsv.gz",
    separator="\t",
    null_values="\\N", # to handle missing values
    quote_char=None,   # to avoid issues with quotes in the data
)
ratings_df.head()

shape: (5, 3)
┌───────────┬───────────────┬──────────┐
│ tconst    ┆ averageRating ┆ numVotes │
│ ---       ┆ ---           ┆ ---      │
│ str       ┆ f64           ┆ i64      │
╞═══════════╪═══════════════╪══════════╡
│ tt0000001 ┆ 5.7           ┆ 2216     │
│ tt0000002 ┆ 5.4           ┆ 321      │
│ tt0000003 ┆ 6.4           ┆ 2354     │
│ tt0000004 ┆ 5.1           ┆ 193      │
│ tt0000005 ┆ 6.2           ┆ 3069     │
└───────────┴───────────────┴──────────┘

In [14]:
ratings_df.shape

(1693823, 3)

## Unificar Datasets Abiertos

In [15]:
# merge the two dataframes on the tconst column, which is the unique identifier for each title in the IMDB dataset
movies_df = (
    basics_df
    .filter(pl.col("titleType") == "movie")  # filter for movies only
    .select([
        pl.col("tconst").alias("imdb_movie_id"), # rename the column to imdb_movie_id
        pl.col("primaryTitle").alias("title"), # rename the column to title
        pl.col("startYear").cast(pl.Int32).alias("year"), # rename the column to year and cast it to Int32
        pl.col("genres") # keep the genres column
    ])
    .join(
        ratings_df.select(["tconst", "averageRating", "numVotes"]), # select only the necessary columns from ratings_df
        left_on="imdb_movie_id",    # join on the imdb_movie_id column from basics_df
        right_on="tconst"           # join on the tconst column from ratings_df
    )
    .rename({       # rename columns in the merged dataframe
        "averageRating": "imdb_rating", # rename the column to imdb_rating
        "numVotes": "imdb_votes"        # rename the column to imdb_votes
    })
    .filter(
        (pl.col("imdb_votes") >= 1000)   # filter for movies with at least 1000 votes
    )
)

In [16]:
movies_df.head()

shape: (5, 6)
┌───────────────┬───────────────────┬──────┬────────────────────────────┬─────────────┬────────────┐
│ imdb_movie_id ┆ title             ┆ year ┆ genres                     ┆ imdb_rating ┆ imdb_votes │
│ ---           ┆ ---               ┆ ---  ┆ ---                        ┆ ---         ┆ ---        │
│ str           ┆ str               ┆ i32  ┆ str                        ┆ f64         ┆ i64        │
╞═══════════════╪═══════════════════╪══════╪════════════════════════════╪═════════════╪════════════╡
│ tt0000574     ┆ The Story of the  ┆ 1906 ┆ Action,Adventure,Biography ┆ 6.0         ┆ 1076       │
│               ┆ Kelly Gang        ┆      ┆                            ┆             ┆            │
│ tt0002130     ┆ Dante's Inferno   ┆ 1911 ┆ Adventure,Drama,Fantasy    ┆ 7.1         ┆ 4176       │
│ tt0002423     ┆ Passion           ┆ 1919 ┆ Biography,Drama,Romance    ┆ 6.7         ┆ 1132       │
│ tt0002844     ┆ Fantômas: In the  ┆ 1913 ┆ Crime,Drama                ┆ 6.9         ┆ 2738       │
│               ┆ Shadow of the…    ┆      ┆                            ┆             ┆            │
│ tt0003014     ┆ Ingeborg Holm     ┆ 1913 ┆ Drama                      ┆ 7.0         ┆ 1614       │
└───────────────┴───────────────────┴──────┴────────────────────────────┴─────────────┴────────────┘

In [17]:
movies_df.write_parquet("data/movies.parquet", compression="snappy")

In [18]:
movies_df.shape

(48692, 6)

## Guardar Ids de películas

In [19]:
# write the imdb_movie_id column to a text file, one id per line
with open("data/movie_ids.txt", "w") as f:
    for movie_id in movies_df["imdb_movie_id"].to_list():
        f.write(f"{movie_id}\n")

In [20]:
!head data/movie_ids.txt

tt0000574
tt0002130
tt0002423
tt0002844
tt0003014
tt0003037
tt0003165
tt0003419
tt0003643
tt0003740

## Descargar Dataset Privado de OMDB API

source: https://www.omdbapi.com/

In [2]:
# !uv add dotenv loguru aiohttp orjson tqdm

Resolved 20 packages in 0.84ms
Checked 17 packages in 2ms

In [5]:
from dotenv import load_dotenv
from loguru import logger
from tqdm import tqdm
from pathlib import Path

import aiohttp
import asyncio

import orjson

from typing import List, Dict

In [6]:
import os

# Cargar variables de entorno desde archivo .env (incluida la API KEY)
load_dotenv()

OMDB_API_KEY = os.getenv("OMDB_API_KEY")

In [9]:
# ========== CONFIGURACIÓN GLOBAL ==========
# URL base de la API de OMDb
OMDB_API_URL = "https://www.omdbapi.com/"
# Número de workers concurrentes para descargar datos en paralelo
# CONCURRENCY = 20
CONCURRENCY = 5
# Número máximo de reintentos por cada ID que falla
MAX_RETRIES = 5
# Ruta del archivo para guardar qué IDs ya fueron procesados
CHECKPOINT_FILE = "data/processed_ids.txt"


# ========== CONFIGURACIÓN DE LOGURU ==========
# Eliminar los manejadores de logs por defecto
logger.remove()
# Agregar un nuevo manejador de logs con formato personalizado y colores
logger.add(
    lambda msg: tqdm.write(msg, end=""),  # Función que imprime el mensaje usando tqdm para no romper la barra de progreso
    # lambda msg: print(msg, end=""),  # Función que imprime el mensaje sin agregar salto de línea extra
    colorize=True,  # Habilitar colores en los logs
    format="<green>{time:HH:mm:ss}</green> | "  # Hora en verde
           "<level>{level}</level> | "  # Nivel de log (INFO, WARNING, etc.)
           "{message}\n",  # Mensaje del log
)


# ========== UTILIDADES DE CHECKPOINT ==========
# Función para cargar IDs que ya fueron procesados
def load_processed_ids() -> set[str]:
    """Carga los IDs de IMDb ya procesados desde el archivo de checkpoint."""
    # Verificar si el archivo de checkpoint existe
    if Path(CHECKPOINT_FILE).exists():
        logger.info(f"Loading checkpoint from {CHECKPOINT_FILE}")
        # Abrir el archivo en modo lectura
        with open(CHECKPOINT_FILE, "r") as f:
            # Leer cada línea, eliminar espacios en blanco, y crear un conjunto
            return set(line.strip() for line in f if line.strip())
    # Si el archivo no existe, retornar un conjunto vacío
    return set()


# Función para guardar un ID procesado en el checkpoint
def append_processed_id(imdb_id: str) -> None:
    """Agrega un único ID de IMDb al archivo de checkpoint."""
    # Abrir el archivo en modo append (añadir al final)
    with open(CHECKPOINT_FILE, "a") as f:
        # Escribir el ID seguido de un salto de línea
        f.write(imdb_id + "\n")


# ========== FUNCIÓN PARA UN ÚNICO REQUEST A OMDb ==========
# Función asíncrona para obtener datos de una película de OMDb
# async def fetch_one(session, imdb_id):
async def fetch_one(session: aiohttp.ClientSession, imdb_id: str) -> Dict | None:
    """
    Obtiene un registro de OMDb por su ID de IMDb.
    Retorna: {"imdb_id": ..., "raw": <json_de_omdb>} o None si falla permanentemente.
    """
    # Definir los parámetros para el request a OMDb
    params = {
        "i": imdb_id,  # ID de IMDb (ej: tt1234567)
        "apikey": os.getenv("OMDB_API_KEY"),  # API key desde variables de entorno
        "plot": "full",  # Obtener la trama completa de la película
    }
    # Inicializar contador de reintentos
    retries = 0
    # logger.info(params)

    # Bucle que se ejecuta mientras no se alcance el máximo de reintentos
    while retries < MAX_RETRIES:
        try:
            # logger.info(f"[{imdb_id}] AFTER request")
            # Hacer un request GET asíncrono a la API
            async with session.get(OMDB_API_URL, params=params) as resp:
                # logger.info(f"[{imdb_id}] BEFORE request")
                # Obtener el código de estado HTTP
                status = resp.status

                # Manejar error 429: Too Many Requests (limite de rate)
                if status == 429:
                    # Calcular tiempo de espera: 5 segundos por reintento
                    wait = 5 * (retries + 1)
                    logger.warning(f"[{imdb_id}] 429 Too Many Requests — sleeping {wait}s")
                    # Esperar antes de reintentar
                    await asyncio.sleep(wait)
                    # Incrementar contador de reintentos
                    retries += 1
                    # Saltar a la siguiente iteración del bucle
                    continue

                # Manejar errores del servidor (5xx)
                if status >= 500:
                    # Calcular tiempo de espera: 3 segundos por reintento
                    wait = 3 * (retries + 1)
                    logger.warning(f"[{imdb_id}] Server error {status} — retrying in {wait}s")
                    # Esperar antes de reintentar
                    await asyncio.sleep(wait)
                    # Incrementar contador de reintentos
                    retries += 1
                    # Saltar a la siguiente iteración del bucle
                    continue

                # Convertir la respuesta a JSON
                data = await resp.json()

                # Verificar si OMDb retornó un error lógico (ID inválido, etc.)
                if data.get("Response") == "False":
                    # Obtener el mensaje de error de OMDb
                    err = data.get("Error", "Unknown error")
                    logger.error(f"[{imdb_id}] OMDb error: {err}")
                    # Retornar el resultado con el error (para guardar en log)
                    return {"imdb_id": imdb_id, "raw": data}

                # Si todo fue exitoso, retornar los datos (sin generar log para evitar spam)
                return {"imdb_id": imdb_id, "raw": data}

        # Manejar excepción de timeout
        except asyncio.TimeoutError:
            # Incrementar contador de reintentos
            retries += 1
            # Calcular tiempo de espera: 2 segundos por reintento
            wait = 2 * retries
            logger.warning(f"[{imdb_id}] Timeout — retrying in {wait}s")
            # Esperar antes de reintentar
            await asyncio.sleep(wait)

        # Manejar cualquier otra excepción inesperada
        except Exception as e:
            # Incrementar contador de reintentos
            retries += 1
            # Calcular tiempo de espera: 2 segundos por reintento
            wait = 2 * retries
            logger.error(f"[{imdb_id}] Unexpected error: {e} — retrying in {wait}s")
            # Esperar antes de reintentar
            await asyncio.sleep(wait)

    # Si se agotan todos los reintentos, registrar error crítico
    logger.critical(f"[{imdb_id}] FAILED permanently after {MAX_RETRIES} retries")
    # Retornar None para indicar fallo definitivo
    return None


# ========== WORKER: PROCESA IDs DE LA COLA Y ESCRIBE A JSONL ==========
# Función asíncrona que actúa como worker para procesar IDs en paralelo
async def worker(
    worker_id: int,  # Identificador del worker
    session: aiohttp.ClientSession,  # Sesión HTTP compartida
    queue: asyncio.Queue,  # Cola de IDs a procesar
    jsonl_path: Path,  # Ruta del archivo JSONL para guardar resultados
    write_lock: asyncio.Lock,  # Lock para escribir de forma segura en el archivo
    progress: tqdm # Barra de progreso opcional (para mostrar progreso en consola)
):
    # Bucle infinito que procesa IDs de la cola
    while True:
        # Obtener el siguiente ID de la cola (espera si está vacía)
        imdb_id = await queue.get()
        # Verificar si es la señal de terminación (None)
        if imdb_id is None:
            # Marcar la tarea como completada
            queue.task_done()
            # Salir del bucle para terminar el worker
            return

        logger.info(f"Worker {worker_id}: {imdb_id}")

        # Obtener datos de OMDb para este ID
        result = await fetch_one(session, imdb_id)

        # Verificar si el fetch fue exitoso
        if result is not None:
            # Convertir el resultado a formato JSON y luego a string (usando orjson)
            line = orjson.dumps(result).decode("utf-8") + "\n"

            # Usar un lock para asegurar que solo un worker escriba a la vez
            async with write_lock:
                # Abrir el archivo JSONL en modo append
                with open(jsonl_path, "a", encoding="utf-8") as f:
                    # Escribir una línea JSON
                    f.write(line)

            # Guardar el ID como procesado en el checkpoint
            append_processed_id(imdb_id)
        
        # Actualizar la barra de progreso
        progress.update(1)

        # Marcar la tarea como completada en la cola
        queue.task_done()


# ========== FUNCIÓN PRINCIPAL: PIPELINE ASÍNCRONO ==========
# Función asíncrona principal que orquesta todo el descargador
async def main(
    all_ids: List[str],  # Lista de todos los IDs de IMDb a descargar
    output_file: str = "omdb_raw.jsonl",  # Ruta del archivo de salida JSONL
):
    """
    Punto de entrada principal del descargador de OMDb.
    
    - all_ids: lista de IDs de IMDb (formato: ttXXXXXX)
    - output_file: ruta del archivo JSONL para guardar los resultados
    
    Esta función:
    - Salta los IDs que ya fueron procesados
    - Descarga los IDs restantes con concurrencia
    - Guarda cada resultado como una línea JSON en output_file
    - Es segura para reintentar después de crashes
    """
    # Convertir el path a un objeto Path
    jsonl_path = Path(output_file)

    # Cargar los IDs que ya fueron procesados desde el checkpoint
    processed = load_processed_ids()
    # Crear una lista de IDs que aún no han sido procesados
    remaining = [i for i in all_ids if i not in processed]
    # Crear una barra de progreso para mostrar el avance de la descarga
    progress = tqdm(
        total=len(remaining),
        desc="Downloading OMDb",
        unit="movie",
        colour="green",
        dynamic_ncols=True,
    )

    # Registrar información sobre el progreso
    logger.info(f"Total IDs: {len(all_ids)}")
    logger.info(f"Already processed: {len(processed)}")
    logger.info(f"Remaining to fetch: {len(remaining)}")
    logger.info(f"Output JSONL: {jsonl_path}")

    # Si no hay IDs por procesar, salir de la función
    if not remaining:
        logger.success("Nothing to do. All IDs are already processed.")
        return

    # Crear una cola asíncrona para almacenar los IDs a procesar
    queue: asyncio.Queue = asyncio.Queue()
    # Crear un lock para sincronizar escrituras concurrentes
    write_lock = asyncio.Lock()

    # Encolar todos los IDs que falta procesar
    for imdb_id in remaining:
        await queue.put(imdb_id)

    # Configurar un timeout de 40 segundos para cada request HTTP
    timeout = aiohttp.ClientTimeout(total=40)

    # Crear una sesión HTTP asíncrona con el timeout configurado
    async with aiohttp.ClientSession(timeout=timeout) as session:
        # Crear y lanzar múltiples workers en paralelo
        workers = [
            asyncio.create_task(worker(i, session, queue, jsonl_path, write_lock, progress))
            for i in range(CONCURRENCY)
        ]

        # Encolar una señal de terminación (None) para cada worker
        for _ in workers:
            await queue.put(None)

        # Esperar hasta que todos los IDs de la cola hayan sido procesados
        await queue.join()

        # Cancelar cualquier worker que aún esté en ejecución
        for w in workers:
            w.cancel()

    # Cerrar la barra de progreso
    progress.close()

    # Registrar que la descarga completó exitosamente
    logger.success("Download complete.")
    logger.info(f"Results appended to {jsonl_path}")

In [ ]:
# ========== CARGAR LISTA DE IDs Y EJECUTAR EL DESCARGADOR ==========
with open("data/movie_ids.txt") as f:
    # Leer todos los IDs de IMDb desde el archivo, eliminando espacios en blanco
    all_ids = [line.strip() for line in f if line.strip()]

# Run the async downloader
await main(all_ids[:1000], output_file="data/omdb_raw.jsonl")

Downloading OMDb:  44%|████▍     | 444/1000 [04:14<53:30,  5.77s/movie]



Downloading OMDb:  44%|████▍     | 444/1000 [04:14<53:30,  5.77s/movie]



Downloading OMDb:  44%|████▍     | 444/1000 [04:14<53:30,  5.77s/movie]



Downloading OMDb:  44%|████▍     | 444/1000 [04:14<53:30,  5.77s/movie]



Downloading OMDb:  44%|████▍     | 444/1000 [04:14<53:30,  5.77s/movie]



Downloading OMDb:  44%|████▍     | 444/1000 [04:14<53:30,  5.77s/movie]



Downloading OMDb:  44%|████▍     | 444/1000 [04:14<53:30,  5.77s/movie]



Downloading OMDb:  44%|████▍     | 444/1000 [04:14<53:30,  5.77s/movie]



Downloading OMDb:  44%|████▍     | 444/1000 [04:14<53:30,  5.77s/movie]

19:36:51 | INFO | Total IDs: 1000

19:36:51 | INFO | Already processed: 0

19:36:51 | INFO | Remaining to fetch: 1000

19:36:51 | INFO | Output JSONL: data/omdb_raw.jsonl

19:36:51 | INFO | Worker 0: tt0000574

19:36:51 | INFO | Worker 1: tt0002130

19:36:51 | INFO | Worker 2: tt0002423

19:36:51 | INFO | Worker 3: tt0002844

19:36:51 | INFO | Worker 4: tt0003014

Downloading OMDb:  44%|████▍     | 444/1000 [04:15<53:30,  5.77s/movie]




Downloading OMDb:  44%|████▍     | 444/1000 [04:15<53:30,  5.77s/movie]



Downloading OMDb:  44%|████▍     | 444/1000 [04:15<53:30,  5.77s/movie]



Downloading OMDb:  44%|████▍     | 444/1000 [04:15<53:30,  5.77s/movie]



Downloading OMDb:  44%|████▍     | 444/1000 [04:15<53:30,  5.77s/movie]



Downloading OMDb:  44%|████▍     | 444/1000 [04:15<53:30,  5.77s/movie]



Downloading OMDb:  44%|████▍     | 444/1000 [04:15<53:30,  5.77s/movie]



Downloading OMDb:  44%|████▍     | 444/1000 [04:15<53:30,  5.77s/movie]



Downloading OMDb:  44%|████▍     | 444/1000 [04:15<53:30,  5.77s/movie]



Downloading OMDb:  44%|████▍     | 444/1000 [04:15<53:30,  5.77s/movie]

19:36:51 | ERROR | [tt0002423] OMDb error: Request limit reached!

19:36:51 | INFO | Worker 2: tt0003037

19:36:51 | ERROR | [tt0002130] OMDb error: Request limit reached!

19:36:51 | INFO | Worker 1: tt0003165

19:36:51 | ERROR | [tt0002844] OMDb error: Request limit reached!

19:36:51 | INFO | Worker 3: tt0003419

19:36:51 | ERROR | [tt0003014] OMDb error: Request limit reached!

19:36:51 | INFO | Worker 4: tt0003643

19:36:51 | ERROR | [tt0000574] OMDb error: Request limit reached!

19:36:51 | INFO | Worker 0: tt0003740

Downloading OMDb:  44%|████▍     | 444/1000 [04:15<53:30,  5.77s/movie]




Downloading OMDb:  44%|████▍     | 444/1000 [04:15<53:30,  5.77s/movie]



Downloading OMDb:  44%|████▍     | 444/1000 [04:15<53:30,  5.77s/movie]



Downloading OMDb:  44%|████▍     | 444/1000 [04:15<53:30,  5.77s/movie]



Downloading OMDb:  44%|████▍     | 444/1000 [04:15<53:30,  5.77s/movie]



Downloading OMDb:  44%|████▍     | 444/1000 [04:15<53:30,  5.77s/movie]



Downloading OMDb:  44%|████▍     | 444/1000 [04:15<53:30,  5.77s/movie]



Downloading OMDb:  44%|████▍     | 444/1000 [04:15<53:30,  5.77s/movie]



Downloading OMDb:  44%|████▍     | 444/1000 [04:15<53:30,  5.77s/movie]



Downloading OMDb:  44%|████▍     | 444/1000 [04:15<53:30,  5.77s/movie]

19:36:51 | ERROR | [tt0003037] OMDb error: Request limit reached!

19:36:51 | INFO | Worker 2: tt0003772

19:36:51 | ERROR | [tt0003165] OMDb error: Request limit reached!

19:36:51 | INFO | Worker 1: tt0003930

19:36:51 | ERROR | [tt0003419] OMDb error: Request limit reached!

19:36:51 | INFO | Worker 3: tt0003952

19:36:51 | ERROR | [tt0003643] OMDb error: Request limit reached!

19:36:51 | INFO | Worker 4: tt0004026

19:36:51 | ERROR | [tt0003740] OMDb error: Request limit reached!

19:36:51 | INFO | Worker 0: tt0004181

Downloading OMDb:  44%|████▍     | 444/1000 [04:15<53:30,  5.77s/movie]




Downloading OMDb:  44%|████▍     | 444/1000 [04:15<53:30,  5.77s/movie]



Downloading OMDb:  44%|████▍     | 444/1000 [04:15<53:30,  5.77s/movie]



Downloading OMDb:  44%|████▍     | 444/1000 [04:15<53:30,  5.77s/movie]



Downloading OMDb:  44%|████▍     | 444/1000 [04:15<53:30,  5.77s/movie]



Downloading OMDb:  44%|████▍     | 444/1000 [04:15<53:30,  5.77s/movie]



Downloading OMDb:  44%|████▍     | 444/1000 [04:15<53:30,  5.77s/movie]



Downloading OMDb:  44%|████▍     | 444/1000 [04:15<53:30,  5.77s/movie]



Downloading OMDb:  44%|████▍     | 444/1000 [04:15<53:30,  5.77s/movie]



Downloading OMDb:  44%|████▍     | 444/1000 [04:15<53:30,  5.77s/movie]

19:36:52 | ERROR | [tt0003772] OMDb error: Request limit reached!

19:36:52 | INFO | Worker 2: tt0004465

19:36:52 | ERROR | [tt0003930] OMDb error: Request limit reached!

19:36:52 | INFO | Worker 1: tt0004635

19:36:52 | ERROR | [tt0003952] OMDb error: Request limit reached!

19:36:52 | INFO | Worker 3: tt0004707

19:36:52 | ERROR | [tt0004026] OMDb error: Request limit reached!

19:36:52 | INFO | Worker 4: tt0004873

19:36:52 | ERROR | [tt0004181] OMDb error: Request limit reached!

19:36:52 | INFO | Worker 0: tt0004972

Downloading OMDb:  44%|████▍     | 444/1000 [04:15<53:30,  5.77s/movie]




Downloading OMDb:  44%|████▍     | 444/1000 [04:15<53:30,  5.77s/movie]



Downloading OMDb:  44%|████▍     | 444/1000 [04:16<53:30,  5.77s/movie]



Downloading OMDb:  44%|████▍     | 444/1000 [04:16<53:30,  5.77s/movie]



Downloading OMDb:  44%|████▍     | 444/1000 [04:16<53:30,  5.77s/movie]



Downloading OMDb:  44%|████▍     | 444/1000 [04:16<53:30,  5.77s/movie]



Downloading OMDb:  44%|████▍     | 444/1000 [04:16<53:30,  5.77s/movie]



Downloading OMDb:  44%|████▍     | 444/1000 [04:16<53:30,  5.77s/movie]



Downloading OMDb:  44%|████▍     | 444/1000 [04:16<53:30,  5.77s/movie]



Downloading OMDb:  44%|████▍     | 444/1000 [04:16<53:30,  5.77s/movie]

19:36:52 | ERROR | [tt0004465] OMDb error: Request limit reached!

19:36:52 | INFO | Worker 2: tt0005060

19:36:52 | ERROR | [tt0004707] OMDb error: Request limit reached!

19:36:52 | INFO | Worker 3: tt0005078

19:36:52 | ERROR | [tt0004873] OMDb error: Request limit reached!

19:36:52 | INFO | Worker 4: tt0005339

19:36:52 | ERROR | [tt0004635] OMDb error: Request limit reached!

19:36:52 | INFO | Worker 1: tt0005916

19:36:52 | ERROR | [tt0004972] OMDb error: Request limit reached!

19:36:52 | INFO | Worker 0: tt0005951

Downloading OMDb:  44%|████▍     | 444/1000 [04:16<53:30,  5.77s/movie]




Downloading OMDb:  44%|████▍     | 444/1000 [04:16<53:30,  5.77s/movie]



Downloading OMDb:  44%|████▍     | 444/1000 [04:16<53:30,  5.77s/movie]



Downloading OMDb:  44%|████▍     | 444/1000 [04:16<53:30,  5.77s/movie]



Downloading OMDb:  44%|████▍     | 444/1000 [04:16<53:30,  5.77s/movie]



Downloading OMDb:  44%|████▍     | 444/1000 [04:16<53:30,  5.77s/movie]



Downloading OMDb:  44%|████▍     | 444/1000 [04:16<53:30,  5.77s/movie]



Downloading OMDb:  44%|████▍     | 444/1000 [04:16<53:30,  5.77s/movie]



Downloading OMDb:  44%|████▍     | 444/1000 [04:16<53:30,  5.77s/movie]



Downloading OMDb:  44%|████▍     | 444/1000 [04:16<53:30,  5.77s/movie]

19:36:52 | ERROR | [tt0005060] OMDb error: Request limit reached!

19:36:52 | INFO | Worker 2: tt0005960

19:36:52 | ERROR | [tt0005078] OMDb error: Request limit reached!

19:36:52 | INFO | Worker 3: tt0006206

19:36:52 | ERROR | [tt0005339] OMDb error: Request limit reached!

19:36:52 | INFO | Worker 4: tt0006333

19:36:52 | ERROR | [tt0005916] OMDb error: Request limit reached!

19:36:52 | INFO | Worker 1: tt0006780

19:36:52 | ERROR | [tt0005951] OMDb error: Request limit reached!

19:36:52 | INFO | Worker 0: tt0006864

Downloading OMDb:  44%|████▍     | 444/1000 [04:16<53:30,  5.77s/movie]




Downloading OMDb:  44%|████▍     | 444/1000 [04:16<53:30,  5.77s/movie]



Downloading OMDb:  44%|████▍     | 444/1000 [04:16<53:30,  5.77s/movie]



Downloading OMDb:  44%|████▍     | 444/1000 [04:16<53:30,  5.77s/movie]



Downloading OMDb:  44%|████▍     | 444/1000 [04:16<53:30,  5.77s/movie]



Downloading OMDb:  44%|████▍     | 444/1000 [04:16<53:30,  5.77s/movie]



Downloading OMDb:  44%|████▍     | 444/1000 [04:16<53:30,  5.77s/movie]



Downloading OMDb:  44%|████▍     | 444/1000 [04:16<53:30,  5.77s/movie]



Downloading OMDb:  44%|████▍     | 444/1000 [04:16<53:30,  5.77s/movie]



Downloading OMDb:  44%|████▍     | 444/1000 [04:16<53:30,  5.77s/movie]

19:36:52 | ERROR | [tt0005960] OMDb error: Request limit reached!

19:36:52 | INFO | Worker 2: tt0006886

19:36:52 | ERROR | [tt0006206] OMDb error: Request limit reached!

19:36:52 | INFO | Worker 3: tt0008443

19:36:52 | ERROR | [tt0006333] OMDb error: Request limit reached!

19:36:52 | INFO | Worker 4: tt0008663

19:36:52 | ERROR | [tt0006780] OMDb error: Request limit reached!

19:36:52 | INFO | Worker 1: tt0008879

19:36:52 | ERROR | [tt0006864] OMDb error: Request limit reached!

19:36:52 | INFO | Worker 0: tt0008891

Downloading OMDb:  44%|████▍     | 444/1000 [04:16<53:30,  5.77s/movie]




Downloading OMDb:  44%|████▍     | 444/1000 [04:16<53:30,  5.77s/movie]



Downloading OMDb:  44%|████▍     | 444/1000 [04:16<53:30,  5.77s/movie]



Downloading OMDb:  44%|████▍     | 444/1000 [04:16<53:30,  5.77s/movie]



Downloading OMDb:  44%|████▍     | 444/1000 [04:16<53:30,  5.77s/movie]



Downloading OMDb:  44%|████▍     | 444/1000 [04:16<53:30,  5.77s/movie]



Downloading OMDb:  44%|████▍     | 444/1000 [04:16<53:30,  5.77s/movie]



Downloading OMDb:  44%|████▍     | 444/1000 [04:16<53:30,  5.77s/movie]



Downloading OMDb:  44%|████▍     | 444/1000 [04:16<53:30,  5.77s/movie]



Downloading OMDb:  44%|████▍     | 444/1000 [04:16<53:30,  5.77s/movie]

19:36:53 | ERROR | [tt0006886] OMDb error: Request limit reached!

19:36:53 | INFO | Worker 2: tt0009150

19:36:53 | ERROR | [tt0008443] OMDb error: Request limit reached!

19:36:53 | INFO | Worker 3: tt0009369

19:36:53 | ERROR | [tt0008663] OMDb error: Request limit reached!

19:36:53 | INFO | Worker 4: tt0009652

19:36:53 | ERROR | [tt0008879] OMDb error: Request limit reached!

19:36:53 | INFO | Worker 1: tt0009682

19:36:53 | ERROR | [tt0008891] OMDb error: Request limit reached!

19:36:53 | INFO | Worker 0: tt0009878

Downloading OMDb:  44%|████▍     | 444/1000 [04:17<53:30,  5.77s/movie]




Downloading OMDb:  44%|████▍     | 444/1000 [04:17<53:30,  5.77s/movie]



Downloading OMDb:  44%|████▍     | 444/1000 [04:17<53:30,  5.77s/movie]



Downloading OMDb:  44%|████▍     | 444/1000 [04:17<53:30,  5.77s/movie]



Downloading OMDb:  44%|████▍     | 444/1000 [04:17<53:30,  5.77s/movie]



Downloading OMDb:  44%|████▍     | 444/1000 [04:17<53:30,  5.77s/movie]



Downloading OMDb:  44%|████▍     | 444/1000 [04:17<53:30,  5.77s/movie]



Downloading OMDb:  44%|████▍     | 444/1000 [04:17<53:30,  5.77s/movie]



Downloading OMDb:  44%|████▍     | 444/1000 [04:17<53:30,  5.77s/movie]



Downloading OMDb:  44%|████▍     | 444/1000 [04:17<53:30,  5.77s/movie]

19:36:53 | ERROR | [tt0009150] OMDb error: Request limit reached!

19:36:53 | INFO | Worker 2: tt0009892

19:36:53 | ERROR | [tt0009369] OMDb error: Request limit reached!

19:36:53 | INFO | Worker 3: tt0009893

19:36:53 | ERROR | [tt0009652] OMDb error: Request limit reached!

19:36:53 | INFO | Worker 4: tt0009900

19:36:53 | ERROR | [tt0009682] OMDb error: Request limit reached!

19:36:53 | INFO | Worker 1: tt0009937

19:36:53 | ERROR | [tt0009878] OMDb error: Request limit reached!

19:36:53 | INFO | Worker 0: tt0009968

Downloading OMDb:  44%|████▍     | 444/1000 [04:17<53:30,  5.77s/movie]




Downloading OMDb:  44%|████▍     | 444/1000 [04:17<53:30,  5.77s/movie]



Downloading OMDb:  44%|████▍     | 444/1000 [04:17<53:30,  5.77s/movie]



Downloading OMDb:  44%|████▍     | 444/1000 [04:17<53:30,  5.77s/movie]



Downloading OMDb:  44%|████▍     | 444/1000 [04:17<53:30,  5.77s/movie]



Downloading OMDb:  44%|████▍     | 444/1000 [04:17<53:30,  5.77s/movie]



Downloading OMDb:  44%|████▍     | 444/1000 [04:17<53:30,  5.77s/movie]



Downloading OMDb:  44%|████▍     | 444/1000 [04:17<53:30,  5.77s/movie]



Downloading OMDb:  44%|████▍     | 444/1000 [04:17<53:30,  5.77s/movie]



Downloading OMDb:  44%|████▍     | 444/1000 [04:17<53:30,  5.77s/movie]

19:36:53 | ERROR | [tt0009892] OMDb error: Request limit reached!

19:36:53 | INFO | Worker 2: tt0010040

19:36:53 | ERROR | [tt0009900] OMDb error: Request limit reached!

19:36:53 | INFO | Worker 4: tt0010071

19:36:53 | ERROR | [tt0009968] OMDb error: Request limit reached!

19:36:53 | INFO | Worker 0: tt0010247

19:36:53 | ERROR | [tt0009893] OMDb error: Request limit reached!

19:36:53 | INFO | Worker 3: tt0010267

19:36:53 | ERROR | [tt0009937] OMDb error: Request limit reached!

19:36:53 | INFO | Worker 1: tt0010281

Downloading OMDb:  44%|████▍     | 444/1000 [04:17<53:30,  5.77s/movie]




Downloading OMDb:  44%|████▍     | 444/1000 [04:17<53:30,  5.77s/movie]



Downloading OMDb:  44%|████▍     | 444/1000 [04:17<53:30,  5.77s/movie]



Downloading OMDb:  44%|████▍     | 444/1000 [04:17<53:30,  5.77s/movie]



Downloading OMDb:  44%|████▍     | 444/1000 [04:17<53:30,  5.77s/movie]



Downloading OMDb:  44%|████▍     | 444/1000 [04:17<53:30,  5.77s/movie]



Downloading OMDb:  44%|████▍     | 444/1000 [04:17<53:30,  5.77s/movie]



Downloading OMDb:  44%|████▍     | 444/1000 [04:17<53:30,  5.77s/movie]



Downloading OMDb:  44%|████▍     | 444/1000 [04:17<53:30,  5.77s/movie]



Downloading OMDb:  44%|████▍     | 444/1000 [04:17<53:30,  5.77s/movie]

19:36:53 | ERROR | [tt0010040] OMDb error: Request limit reached!

19:36:53 | INFO | Worker 2: tt0010307

19:36:53 | ERROR | [tt0010071] OMDb error: Request limit reached!

19:36:53 | INFO | Worker 4: tt0010323

19:36:53 | ERROR | [tt0010247] OMDb error: Request limit reached!

19:36:53 | INFO | Worker 0: tt0010418

19:36:53 | ERROR | [tt0010267] OMDb error: Request limit reached!

19:36:53 | INFO | Worker 3: tt0010598

19:36:53 | ERROR | [tt0010281] OMDb error: Request limit reached!

19:36:53 | INFO | Worker 1: tt0010600

Downloading OMDb:  44%|████▍     | 444/1000 [04:17<53:30,  5.77s/movie]




Downloading OMDb:  44%|████▍     | 444/1000 [04:17<53:30,  5.77s/movie]



Downloading OMDb:  44%|████▍     | 444/1000 [04:17<53:30,  5.77s/movie]



Downloading OMDb:  44%|████▍     | 444/1000 [04:17<53:30,  5.77s/movie]



Downloading OMDb:  44%|████▍     | 444/1000 [04:17<53:30,  5.77s/movie]



Downloading OMDb:  44%|████▍     | 444/1000 [04:17<53:30,  5.77s/movie]



Downloading OMDb:  44%|████▍     | 444/1000 [04:17<53:30,  5.77s/movie]



Downloading OMDb:  44%|████▍     | 444/1000 [04:17<53:30,  5.77s/movie]



Downloading OMDb:  44%|████▍     | 444/1000 [04:17<53:30,  5.77s/movie]



Downloading OMDb:  44%|████▍     | 444/1000 [04:17<53:30,  5.77s/movie]

19:36:54 | ERROR | [tt0010307] OMDb error: Request limit reached!

19:36:54 | INFO | Worker 2: tt0010726

19:36:54 | ERROR | [tt0010323] OMDb error: Request limit reached!

19:36:54 | INFO | Worker 4: tt0010806

19:36:54 | ERROR | [tt0010418] OMDb error: Request limit reached!

19:36:54 | INFO | Worker 0: tt0010879

19:36:54 | ERROR | [tt0010598] OMDb error: Request limit reached!

19:36:54 | INFO | Worker 3: tt0011000

19:36:54 | ERROR | [tt0010600] OMDb error: Request limit reached!

19:36:54 | INFO | Worker 1: tt0011130

Downloading OMDb:  44%|████▍     | 444/1000 [04:18<53:30,  5.77s/movie]




Downloading OMDb:  44%|████▍     | 444/1000 [04:18<53:30,  5.77s/movie]



Downloading OMDb:  44%|████▍     | 444/1000 [04:18<53:30,  5.77s/movie]



Downloading OMDb:  44%|████▍     | 444/1000 [04:18<53:30,  5.77s/movie]



Downloading OMDb:  44%|████▍     | 444/1000 [04:18<53:30,  5.77s/movie]



Downloading OMDb:  44%|████▍     | 444/1000 [04:18<53:30,  5.77s/movie]



Downloading OMDb:  44%|████▍     | 444/1000 [04:18<53:30,  5.77s/movie]



Downloading OMDb:  44%|████▍     | 444/1000 [04:18<53:30,  5.77s/movie]



Downloading OMDb:  44%|████▍     | 444/1000 [04:18<53:30,  5.77s/movie]



Downloading OMDb:  44%|████▍     | 444/1000 [04:18<53:30,  5.77s/movie]

19:36:54 | ERROR | [tt0010726] OMDb error: Request limit reached!

19:36:54 | INFO | Worker 2: tt0011157

19:36:54 | ERROR | [tt0010806] OMDb error: Request limit reached!

19:36:54 | INFO | Worker 4: tt0011221

19:36:54 | ERROR | [tt0010879] OMDb error: Request limit reached!

19:36:54 | INFO | Worker 0: tt0011237

19:36:54 | ERROR | [tt0011000] OMDb error: Request limit reached!

19:36:54 | INFO | Worker 3: tt0011387

19:36:54 | ERROR | [tt0011130] OMDb error: Request limit reached!

19:36:54 | INFO | Worker 1: tt0011439

Downloading OMDb:  44%|████▍     | 444/1000 [04:18<53:30,  5.77s/movie]




Downloading OMDb:  44%|████▍     | 444/1000 [04:18<53:30,  5.77s/movie]



Downloading OMDb:  44%|████▍     | 444/1000 [04:18<53:30,  5.77s/movie]



Downloading OMDb:  44%|████▍     | 444/1000 [04:18<53:30,  5.77s/movie]



Downloading OMDb:  44%|████▍     | 444/1000 [04:18<53:30,  5.77s/movie]



Downloading OMDb:  44%|████▍     | 444/1000 [04:18<53:30,  5.77s/movie]



Downloading OMDb:  44%|████▍     | 444/1000 [04:18<53:30,  5.77s/movie]



Downloading OMDb:  44%|████▍     | 444/1000 [04:18<53:30,  5.77s/movie]



Downloading OMDb:  44%|████▍     | 444/1000 [04:18<53:30,  5.77s/movie]



Downloading OMDb:  44%|████▍     | 444/1000 [04:18<53:30,  5.77s/movie]

19:36:54 | ERROR | [tt0011157] OMDb error: Request limit reached!

19:36:54 | INFO | Worker 2: tt0011565

19:36:54 | ERROR | [tt0011221] OMDb error: Request limit reached!

19:36:54 | INFO | Worker 4: tt0011607

19:36:54 | ERROR | [tt0011237] OMDb error: Request limit reached!

19:36:54 | INFO | Worker 0: tt0011652

19:36:54 | ERROR | [tt0011439] OMDb error: Request limit reached!

19:36:54 | INFO | Worker 1: tt0011723

19:36:54 | ERROR | [tt0011387] OMDb error: Request limit reached!

19:36:54 | INFO | Worker 3: tt0011841

Downloading OMDb:  44%|████▍     | 444/1000 [04:18<53:30,  5.77s/movie]




Downloading OMDb:  44%|████▍     | 444/1000 [04:18<53:30,  5.77s/movie]



Downloading OMDb:  44%|████▍     | 444/1000 [04:18<53:30,  5.77s/movie]



Downloading OMDb:  44%|████▍     | 444/1000 [04:18<53:30,  5.77s/movie]



Downloading OMDb:  44%|████▍     | 444/1000 [04:18<53:30,  5.77s/movie]



Downloading OMDb:  44%|████▍     | 444/1000 [04:18<53:30,  5.77s/movie]



Downloading OMDb:  44%|████▍     | 444/1000 [04:18<53:30,  5.77s/movie]



Downloading OMDb:  44%|████▍     | 444/1000 [04:18<53:30,  5.77s/movie]



Downloading OMDb:  44%|████▍     | 444/1000 [04:18<53:30,  5.77s/movie]



Downloading OMDb:  44%|████▍     | 444/1000 [04:18<53:30,  5.77s/movie]

19:36:54 | ERROR | [tt0011565] OMDb error: Request limit reached!

19:36:54 | INFO | Worker 2: tt0011865

19:36:54 | ERROR | [tt0011607] OMDb error: Request limit reached!

19:36:54 | INFO | Worker 4: tt0011870

19:36:54 | ERROR | [tt0011652] OMDb error: Request limit reached!

19:36:54 | INFO | Worker 0: tt0011904

19:36:54 | ERROR | [tt0011723] OMDb error: Request limit reached!

19:36:54 | INFO | Worker 1: tt0011909

19:36:54 | ERROR | [tt0011841] OMDb error: Request limit reached!

19:36:54 | INFO | Worker 3: tt0011960

Downloading OMDb:  44%|████▍     | 444/1000 [04:18<53:30,  5.77s/movie]




Downloading OMDb:  44%|████▍     | 444/1000 [04:18<53:30,  5.77s/movie]



Downloading OMDb:  44%|████▍     | 444/1000 [04:18<53:30,  5.77s/movie]



Downloading OMDb:  44%|████▍     | 444/1000 [04:18<53:30,  5.77s/movie]



Downloading OMDb:  44%|████▍     | 444/1000 [04:18<53:30,  5.77s/movie]



Downloading OMDb:  44%|████▍     | 444/1000 [04:18<53:30,  5.77s/movie]



Downloading OMDb:  44%|████▍     | 444/1000 [04:18<53:30,  5.77s/movie]



Downloading OMDb:  44%|████▍     | 444/1000 [04:18<53:30,  5.77s/movie]



Downloading OMDb:  44%|████▍     | 444/1000 [04:18<53:30,  5.77s/movie]



Downloading OMDb:  44%|████▍     | 444/1000 [04:18<53:30,  5.77s/movie]

19:36:55 | ERROR | [tt0011865] OMDb error: Request limit reached!

19:36:55 | INFO | Worker 2: tt0012027

19:36:55 | ERROR | [tt0011870] OMDb error: Request limit reached!

19:36:55 | INFO | Worker 4: tt0012190

19:36:55 | ERROR | [tt0011904] OMDb error: Request limit reached!

19:36:55 | INFO | Worker 0: tt0012349

19:36:55 | ERROR | [tt0011909] OMDb error: Request limit reached!

19:36:55 | INFO | Worker 1: tt0012364

19:36:55 | ERROR | [tt0011960] OMDb error: Request limit reached!

19:36:55 | INFO | Worker 3: tt0012494

Downloading OMDb:  44%|████▍     | 444/1000 [04:19<53:30,  5.77s/movie]




Downloading OMDb:  44%|████▍     | 444/1000 [04:19<53:30,  5.77s/movie]



Downloading OMDb:  44%|████▍     | 444/1000 [04:19<53:30,  5.77s/movie]



Downloading OMDb:  44%|████▍     | 444/1000 [04:19<53:30,  5.77s/movie]



Downloading OMDb:  44%|████▍     | 444/1000 [04:19<53:30,  5.77s/movie]



Downloading OMDb:  44%|████▍     | 444/1000 [04:19<53:30,  5.77s/movie]



Downloading OMDb:  44%|████▍     | 444/1000 [04:19<53:30,  5.77s/movie]



Downloading OMDb:  44%|████▍     | 444/1000 [04:19<53:30,  5.77s/movie]



Downloading OMDb:  44%|████▍     | 444/1000 [04:19<53:30,  5.77s/movie]



Downloading OMDb:  44%|████▍     | 444/1000 [04:19<53:30,  5.77s/movie]

19:36:55 | ERROR | [tt0012027] OMDb error: Request limit reached!

19:36:55 | INFO | Worker 2: tt0012532

19:36:55 | ERROR | [tt0012190] OMDb error: Request limit reached!

19:36:55 | INFO | Worker 4: tt0012642

19:36:55 | ERROR | [tt0012349] OMDb error: Request limit reached!

19:36:55 | INFO | Worker 0: tt0012651

19:36:55 | ERROR | [tt0012364] OMDb error: Request limit reached!

19:36:55 | INFO | Worker 1: tt0012675

19:36:55 | ERROR | [tt0012494] OMDb error: Request limit reached!

19:36:55 | INFO | Worker 3: tt0012752

Downloading OMDb:  44%|████▍     | 444/1000 [04:19<53:30,  5.77s/movie]




Downloading OMDb:  44%|████▍     | 444/1000 [04:19<53:30,  5.77s/movie]



Downloading OMDb:  44%|████▍     | 444/1000 [04:19<53:30,  5.77s/movie]



Downloading OMDb:  44%|████▍     | 444/1000 [04:19<53:30,  5.77s/movie]



Downloading OMDb:  44%|████▍     | 444/1000 [04:19<53:30,  5.77s/movie]



Downloading OMDb:  44%|████▍     | 444/1000 [04:19<53:30,  5.77s/movie]

19:36:55 | ERROR | [tt0012642] OMDb error: Request limit reached!

19:36:55 | INFO | Worker 4: tt0012763

19:36:55 | ERROR | [tt0012675] OMDb error: Request limit reached!

19:36:55 | INFO | Worker 1: tt0012938

19:36:55 | ERROR | [tt0012532] OMDb error: Request limit reached!

19:36:55 | INFO | Worker 2: tt0012952

Downloading OMDb:  44%|████▍     | 444/1000 [04:19<53:30,  5.77s/movie]




Downloading OMDb:  44%|████▍     | 444/1000 [04:19<53:30,  5.77s/movie]

19:36:55 | ERROR | [tt0012763] OMDb error: Request limit reached!

19:36:55 | INFO | Worker 4: tt0013075

Downloading OMDb:  44%|████▍     | 444/1000 [04:20<53:30,  5.77s/movie]



Downloading OMDb:  44%|████▍     | 444/1000 [04:20<53:30,  5.77s/movie]



Downloading OMDb:  44%|████▍     | 444/1000 [04:20<53:30,  5.77s/movie]




Downloading OMDb:  44%|████▍     | 444/1000 [04:20<53:30,  5.77s/movie]



Downloading OMDb:  44%|████▍     | 444/1000 [04:20<53:30,  5.77s/movie]



Downloading OMDb:  44%|████▍     | 444/1000 [04:20<53:30,  5.77s/movie]



Downloading OMDb:  44%|████▍     | 444/1000 [04:20<53:30,  5.77s/movie]



Downloading OMDb:  44%|████▍     | 444/1000 [04:20<53:30,  5.77s/movie]



Downloading OMDb:  44%|████▍     | 444/1000 [04:20<53:30,  5.77s/movie]



Downloading OMDb:  44%|████▍     | 444/1000 [04:20<53:30,  5.77s/movie]

19:36:56 | ERROR | [tt0012651] OMDb error: Request limit reached!

19:36:56 | INFO | Worker 0: tt0013086

19:36:56 | ERROR | [tt0012752] OMDb error: Request limit reached!

19:36:56 | INFO | Worker 3: tt0013140

19:36:56 | ERROR | [tt0012952] OMDb error: Request limit reached!

19:36:56 | INFO | Worker 2: tt0013201

19:36:56 | ERROR | [tt0012938] OMDb error: Request limit reached!

19:36:56 | INFO | Worker 1: tt0013257

19:36:56 | ERROR | [tt0013075] OMDb error: Request limit reached!

19:36:56 | INFO | Worker 4: tt0013427

Downloading OMDb:  44%|████▍     | 444/1000 [04:20<53:30,  5.77s/movie]




Downloading OMDb:  44%|████▍     | 444/1000 [04:20<53:30,  5.77s/movie]



Downloading OMDb:  44%|████▍     | 444/1000 [04:20<53:30,  5.77s/movie]



Downloading OMDb:  44%|████▍     | 444/1000 [04:20<53:30,  5.77s/movie]



Downloading OMDb:  44%|████▍     | 444/1000 [04:20<53:30,  5.77s/movie]



Downloading OMDb:  44%|████▍     | 444/1000 [04:20<53:30,  5.77s/movie]



Downloading OMDb:  44%|████▍     | 444/1000 [04:20<53:30,  5.77s/movie]



Downloading OMDb:  44%|████▍     | 444/1000 [04:20<53:30,  5.77s/movie]



Downloading OMDb:  44%|████▍     | 444/1000 [04:20<53:30,  5.77s/movie]



Downloading OMDb:  44%|████▍     | 444/1000 [04:20<53:30,  5.77s/movie]

19:36:56 | ERROR | [tt0013086] OMDb error: Request limit reached!

19:36:56 | INFO | Worker 0: tt0013442

19:36:56 | ERROR | [tt0013140] OMDb error: Request limit reached!

19:36:56 | INFO | Worker 3: tt0013496

19:36:56 | ERROR | [tt0013427] OMDb error: Request limit reached!

19:36:56 | INFO | Worker 4: tt0013556

19:36:56 | ERROR | [tt0013201] OMDb error: Request limit reached!

19:36:57 | INFO | Worker 2: tt0013571

19:36:57 | ERROR | [tt0013257] OMDb error: Request limit reached!

19:36:57 | INFO | Worker 1: tt0013579

Downloading OMDb:  44%|████▍     | 444/1000 [04:20<53:30,  5.77s/movie]




Downloading OMDb:  44%|████▍     | 444/1000 [04:20<53:30,  5.77s/movie]



Downloading OMDb:  44%|████▍     | 444/1000 [04:20<53:30,  5.77s/movie]



Downloading OMDb:  44%|████▍     | 444/1000 [04:20<53:30,  5.77s/movie]



Downloading OMDb:  44%|████▍     | 444/1000 [04:20<53:30,  5.77s/movie]



Downloading OMDb:  44%|████▍     | 444/1000 [04:20<53:30,  5.77s/movie]



Downloading OMDb:  44%|████▍     | 444/1000 [04:20<53:30,  5.77s/movie]



Downloading OMDb:  44%|████▍     | 444/1000 [04:20<53:30,  5.77s/movie]



Downloading OMDb:  44%|████▍     | 444/1000 [04:20<53:30,  5.77s/movie]



Downloading OMDb:  44%|████▍     | 444/1000 [04:20<53:30,  5.77s/movie]

19:36:57 | ERROR | [tt0013442] OMDb error: Request limit reached!

19:36:57 | INFO | Worker 0: tt0013688

19:36:57 | ERROR | [tt0013496] OMDb error: Request limit reached!

19:36:57 | INFO | Worker 3: tt0013750

19:36:57 | ERROR | [tt0013556] OMDb error: Request limit reached!

19:36:57 | INFO | Worker 4: tt0013933

19:36:57 | ERROR | [tt0013571] OMDb error: Request limit reached!

19:36:57 | INFO | Worker 2: tt0014029

19:36:57 | ERROR | [tt0013579] OMDb error: Request limit reached!

19:36:57 | INFO | Worker 1: tt0014109

Downloading OMDb:  44%|████▍     | 444/1000 [04:21<53:30,  5.77s/movie]




Downloading OMDb:  44%|████▍     | 444/1000 [04:21<53:30,  5.77s/movie]



Downloading OMDb:  44%|████▍     | 444/1000 [04:21<53:30,  5.77s/movie]



Downloading OMDb:  44%|████▍     | 444/1000 [04:21<53:30,  5.77s/movie]



Downloading OMDb:  44%|████▍     | 444/1000 [04:21<53:30,  5.77s/movie]



Downloading OMDb:  44%|████▍     | 444/1000 [04:21<53:30,  5.77s/movie]



Downloading OMDb:  44%|████▍     | 444/1000 [04:21<53:30,  5.77s/movie]



Downloading OMDb:  44%|████▍     | 444/1000 [04:21<53:30,  5.77s/movie]



Downloading OMDb:  44%|████▍     | 444/1000 [04:21<53:30,  5.77s/movie]



Downloading OMDb:  44%|████▍     | 444/1000 [04:21<53:30,  5.77s/movie]

19:36:57 | ERROR | [tt0013688] OMDb error: Request limit reached!

19:36:57 | INFO | Worker 0: tt0014142

19:36:57 | ERROR | [tt0013933] OMDb error: Request limit reached!

19:36:57 | INFO | Worker 4: tt0014205

19:36:57 | ERROR | [tt0014029] OMDb error: Request limit reached!

19:36:57 | INFO | Worker 2: tt0014341

19:36:57 | ERROR | [tt0013750] OMDb error: Request limit reached!

19:36:57 | INFO | Worker 3: tt0014358

19:36:57 | ERROR | [tt0014109] OMDb error: Request limit reached!

19:36:57 | INFO | Worker 1: tt0014417

Downloading OMDb:  44%|████▍     | 444/1000 [04:21<53:30,  5.77s/movie]




Downloading OMDb:  44%|████▍     | 444/1000 [04:21<53:30,  5.77s/movie]



Downloading OMDb:  44%|████▍     | 444/1000 [04:21<53:30,  5.77s/movie]



Downloading OMDb:  44%|████▍     | 444/1000 [04:21<53:30,  5.77s/movie]



Downloading OMDb:  44%|████▍     | 444/1000 [04:21<53:30,  5.77s/movie]



Downloading OMDb:  44%|████▍     | 444/1000 [04:21<53:30,  5.77s/movie]



Downloading OMDb:  44%|████▍     | 444/1000 [04:21<53:30,  5.77s/movie]



Downloading OMDb:  44%|████▍     | 444/1000 [04:21<53:30,  5.77s/movie]



Downloading OMDb:  44%|████▍     | 444/1000 [04:21<53:30,  5.77s/movie]



Downloading OMDb:  44%|████▍     | 444/1000 [04:21<53:30,  5.77s/movie]

19:36:57 | ERROR | [tt0014142] OMDb error: Request limit reached!

19:36:57 | INFO | Worker 0: tt0014429

19:36:57 | ERROR | [tt0014205] OMDb error: Request limit reached!

19:36:57 | INFO | Worker 4: tt0014497

19:36:57 | ERROR | [tt0014341] OMDb error: Request limit reached!

19:36:57 | INFO | Worker 2: tt0014532

19:36:57 | ERROR | [tt0014417] OMDb error: Request limit reached!

19:36:57 | INFO | Worker 1: tt0014538

19:36:57 | ERROR | [tt0014358] OMDb error: Request limit reached!

19:36:57 | INFO | Worker 3: tt0014586

Downloading OMDb:  44%|████▍     | 444/1000 [04:21<53:30,  5.77s/movie]




Downloading OMDb:  44%|████▍     | 444/1000 [04:21<53:30,  5.77s/movie]



Downloading OMDb:  44%|████▍     | 444/1000 [04:21<53:30,  5.77s/movie]



Downloading OMDb:  44%|████▍     | 444/1000 [04:21<53:30,  5.77s/movie]



Downloading OMDb:  44%|████▍     | 444/1000 [04:21<53:30,  5.77s/movie]



Downloading OMDb:  44%|████▍     | 444/1000 [04:21<53:30,  5.77s/movie]



Downloading OMDb:  44%|████▍     | 444/1000 [04:21<53:30,  5.77s/movie]



Downloading OMDb:  44%|████▍     | 444/1000 [04:21<53:30,  5.77s/movie]



Downloading OMDb:  44%|████▍     | 444/1000 [04:21<53:30,  5.77s/movie]



Downloading OMDb:  44%|████▍     | 444/1000 [04:21<53:30,  5.77s/movie]

19:36:57 | ERROR | [tt0014429] OMDb error: Request limit reached!

19:36:57 | INFO | Worker 0: tt0014611

19:36:57 | ERROR | [tt0014497] OMDb error: Request limit reached!

19:36:57 | INFO | Worker 4: tt0014624

19:36:58 | ERROR | [tt0014532] OMDb error: Request limit reached!

19:36:58 | INFO | Worker 2: tt0014646

19:36:58 | ERROR | [tt0014538] OMDb error: Request limit reached!

19:36:58 | INFO | Worker 1: tt0014900

19:36:58 | ERROR | [tt0014586] OMDb error: Request limit reached!

19:36:58 | INFO | Worker 3: tt0014945

Downloading OMDb:  44%|████▍     | 444/1000 [04:21<53:30,  5.77s/movie]




Downloading OMDb:  44%|████▍     | 444/1000 [04:21<53:30,  5.77s/movie]



Downloading OMDb:  44%|████▍     | 444/1000 [04:21<53:30,  5.77s/movie]



Downloading OMDb:  44%|████▍     | 444/1000 [04:21<53:30,  5.77s/movie]



Downloading OMDb:  44%|████▍     | 444/1000 [04:21<53:30,  5.77s/movie]



Downloading OMDb:  44%|████▍     | 444/1000 [04:21<53:30,  5.77s/movie]



Downloading OMDb:  44%|████▍     | 444/1000 [04:21<53:30,  5.77s/movie]



Downloading OMDb:  44%|████▍     | 444/1000 [04:21<53:30,  5.77s/movie]



Downloading OMDb:  45%|████▍     | 449/1000 [04:21<53:42,  5.85s/movie]



Downloading OMDb:  45%|████▍     | 449/1000 [04:21<53:42,  5.85s/movie]

19:36:58 | ERROR | [tt0014611] OMDb error: Request limit reached!

19:36:58 | INFO | Worker 0: tt0014972

19:36:58 | ERROR | [tt0014624] OMDb error: Request limit reached!

19:36:58 | INFO | Worker 4: tt0015002

19:36:58 | ERROR | [tt0014646] OMDb error: Request limit reached!

19:36:58 | INFO | Worker 2: tt0015014

19:36:58 | ERROR | [tt0014900] OMDb error: Request limit reached!

19:36:58 | INFO | Worker 1: tt0015016

19:36:58 | ERROR | [tt0014945] OMDb error: Request limit reached!

19:36:58 | INFO | Worker 3: tt0015039

Downloading OMDb:  45%|████▍     | 449/1000 [04:22<53:42,  5.85s/movie]




Downloading OMDb:  45%|████▍     | 449/1000 [04:22<53:42,  5.85s/movie]



Downloading OMDb:  45%|████▍     | 449/1000 [04:22<53:42,  5.85s/movie]



Downloading OMDb:  45%|████▍     | 449/1000 [04:22<53:42,  5.85s/movie]



Downloading OMDb:  45%|████▍     | 449/1000 [04:22<53:42,  5.85s/movie]



Downloading OMDb:  45%|████▍     | 449/1000 [04:22<53:42,  5.85s/movie]



Downloading OMDb:  45%|████▍     | 449/1000 [04:22<53:42,  5.85s/movie]



Downloading OMDb:  45%|████▍     | 449/1000 [04:22<53:42,  5.85s/movie]



Downloading OMDb:  45%|████▍     | 449/1000 [04:22<53:42,  5.85s/movie]




Downloading OMDb:  45%|████▍     | 449/1000 [04:22<53:42,  5.85s/movie]

19:36:58 | ERROR | [tt0014972] OMDb error: Request limit reached!

19:36:58 | INFO | Worker 0: tt0015064

19:36:58 | ERROR | [tt0015002] OMDb error: Request limit reached!

19:36:58 | INFO | Worker 4: tt0015116

19:36:58 | ERROR | [tt0015014] OMDb error: Request limit reached!

19:36:58 | INFO | Worker 2: tt0015119

19:36:58 | ERROR | [tt0015016] OMDb error: Request limit reached!

19:36:58 | INFO | Worker 1: tt0015136

19:36:58 | ERROR | [tt0015039] OMDb error: Request limit reached!

19:36:58 | INFO | Worker 3: tt0015163

Downloading OMDb:  45%|████▍     | 449/1000 [04:22<53:42,  5.85s/movie]



Downloading OMDb:  45%|████▍     | 449/1000 [04:22<53:42,  5.85s/movie]



Downloading OMDb:  45%|████▍     | 449/1000 [04:22<53:42,  5.85s/movie]



Downloading OMDb:  45%|████▍     | 449/1000 [04:22<53:42,  5.85s/movie]



Downloading OMDb:  45%|████▍     | 449/1000 [04:22<53:42,  5.85s/movie]




Downloading OMDb:  45%|████▍     | 449/1000 [04:22<53:42,  5.85s/movie]



Downloading OMDb:  45%|████▍     | 449/1000 [04:22<53:42,  5.85s/movie]



Downloading OMDb:  45%|████▍     | 449/1000 [04:22<53:42,  5.85s/movie]



Downloading OMDb:  45%|████▍     | 449/1000 [04:22<53:42,  5.85s/movie]

19:36:58 | ERROR | [tt0015064] OMDb error: Request limit reached!

19:36:58 | INFO | Worker 0: tt0015167

19:36:58 | ERROR | [tt0015116] OMDb error: Request limit reached!

19:36:58 | INFO | Worker 4: tt0015174

19:36:58 | ERROR | [tt0015119] OMDb error: Request limit reached!

19:36:58 | INFO | Worker 2: tt0015175

19:36:58 | ERROR | [tt0015136] OMDb error: Request limit reached!

19:36:58 | INFO | Worker 1: tt0015202

19:36:58 | ERROR | [tt0015163] OMDb error: Request limit reached!

Downloading OMDb:  45%|████▍     | 449/1000 [04:22<53:42,  5.85s/movie]



Downloading OMDb:  45%|████▍     | 449/1000 [04:22<53:42,  5.85s/movie]




Downloading OMDb:  45%|████▍     | 449/1000 [04:22<53:42,  5.85s/movie]



Downloading OMDb:  45%|████▍     | 449/1000 [04:22<53:42,  5.85s/movie]



Downloading OMDb:  45%|████▍     | 449/1000 [04:22<53:42,  5.85s/movie]



Downloading OMDb:  45%|████▍     | 449/1000 [04:22<53:42,  5.85s/movie]



Downloading OMDb:  45%|████▍     | 449/1000 [04:22<53:42,  5.85s/movie]



Downloading OMDb:  45%|████▍     | 449/1000 [04:22<53:42,  5.85s/movie]



Downloading OMDb:  45%|████▍     | 449/1000 [04:22<53:42,  5.85s/movie]

19:36:58 | INFO | Worker 3: tt0015214

19:36:58 | ERROR | [tt0015167] OMDb error: Request limit reached!

19:36:58 | INFO | Worker 0: tt0015224

19:36:58 | ERROR | [tt0015174] OMDb error: Request limit reached!

19:36:59 | INFO | Worker 4: tt0015324

19:36:59 | ERROR | [tt0015175] OMDb error: Request limit reached!

19:36:59 | INFO | Worker 2: tt0015361

19:36:59 | ERROR | [tt0015202] OMDb error: Request limit reached!

19:36:59 | INFO | Worker 1: tt0015400

Downloading OMDb:  45%|████▍     | 449/1000 [04:22<53:42,  5.85s/movie]




Downloading OMDb:  45%|████▍     | 449/1000 [04:22<53:42,  5.85s/movie]



Downloading OMDb:  45%|████▍     | 449/1000 [04:22<53:42,  5.85s/movie]


Downloading OMDb:  45%|████▍     | 449/1000 [04:22<53:42,  5.85s/movie]



Downloading OMDb:  45%|████▍     | 449/1000 [04:22<53:42,  5.85s/movie]



Downloading OMDb:  45%|████▍     | 449/1000 [04:22<53:42,  5.85s/movie]



Downloading OMDb:  45%|████▍     | 449/1000 [04:22<53:42,  5.85s/movie]



Downloading OMDb:  45%|████▍     | 449/1000 [04:22<53:42,  5.85s/movie]



Downloading OMDb:  45%|████▍     | 449/1000 [04:22<53:42,  5.85s/movie]



Downloading OMDb:  45%|████▍     | 449/1000 [04:22<53:42,  5.85s/movie]

19:36:59 | ERROR | [tt0015214] OMDb error: Request limit reached!

19:36:59 | INFO | Worker 3: tt0015532

19:36:59 | ERROR | [tt0015224] OMDb error: Request limit reached!

19:36:59 | INFO | Worker 0: tt0015624

19:36:59 | ERROR | [tt0015324] OMDb error: Request limit reached!

19:36:59 | INFO | Worker 4: tt0015634

19:36:59 | ERROR | [tt0015361] OMDb error: Request limit reached!

19:36:59 | INFO | Worker 2: tt0015648

19:36:59 | ERROR | [tt0015400] OMDb error: Request limit reached!

19:36:59 | INFO | Worker 1: tt0015768

Downloading OMDb:  45%|████▍     | 449/1000 [04:23<53:42,  5.85s/movie]




Downloading OMDb:  45%|████▍     | 449/1000 [04:23<53:42,  5.85s/movie]



Downloading OMDb:  45%|████▍     | 449/1000 [04:23<53:42,  5.85s/movie]



Downloading OMDb:  45%|████▍     | 449/1000 [04:23<53:42,  5.85s/movie]



Downloading OMDb:  45%|████▍     | 449/1000 [04:23<53:42,  5.85s/movie]



Downloading OMDb:  45%|████▍     | 449/1000 [04:23<53:42,  5.85s/movie]



Downloading OMDb:  45%|████▍     | 449/1000 [04:23<53:42,  5.85s/movie]



Downloading OMDb:  45%|████▍     | 449/1000 [04:23<53:42,  5.85s/movie]



Downloading OMDb:  45%|████▍     | 449/1000 [04:23<53:42,  5.85s/movie]




Downloading OMDb:  45%|████▍     | 449/1000 [04:23<53:42,  5.85s/movie]

19:36:59 | ERROR | [tt0015624] OMDb error: Request limit reached!

19:36:59 | INFO | Worker 0: tt0015772

19:36:59 | ERROR | [tt0015634] OMDb error: Request limit reached!

19:36:59 | INFO | Worker 4: tt0015841

19:36:59 | ERROR | [tt0015768] OMDb error: Request limit reached!

19:36:59 | INFO | Worker 1: tt0015842

19:36:59 | ERROR | [tt0015648] OMDb error: Request limit reached!

19:36:59 | INFO | Worker 2: tt0015863

19:36:59 | ERROR | [tt0015532] OMDb error: Request limit reached!

19:36:59 | INFO | Worker 3: tt0015864

Downloading OMDb:  45%|████▍     | 449/1000 [04:23<53:42,  5.85s/movie]



Downloading OMDb:  45%|████▍     | 449/1000 [04:23<53:42,  5.85s/movie]



Downloading OMDb:  45%|████▍     | 449/1000 [04:23<53:42,  5.85s/movie]



Downloading OMDb:  45%|████▍     | 449/1000 [04:23<53:42,  5.85s/movie]



Downloading OMDb:  45%|████▍     | 449/1000 [04:23<53:42,  5.85s/movie]




Downloading OMDb:  45%|████▍     | 449/1000 [04:23<53:42,  5.85s/movie]



Downloading OMDb:  45%|████▍     | 449/1000 [04:23<53:42,  5.85s/movie]



Downloading OMDb:  45%|████▍     | 449/1000 [04:23<53:42,  5.85s/movie]

19:36:59 | ERROR | [tt0015772] OMDb error: Request limit reached!

19:36:59 | INFO | Worker 0: tt0015873

19:36:59 | ERROR | [tt0015842] OMDb error: Request limit reached!

19:36:59 | INFO | Worker 1: tt0015881

19:36:59 | ERROR | [tt0015863] OMDb error: Request limit reached!

19:36:59 | INFO | Worker 2: tt0016004

19:36:59 | ERROR | [tt0015864] OMDb error: Request limit reached!

19:36:59 | INFO | Worker 3: tt0016028

Downloading OMDb:  45%|████▍     | 449/1000 [04:23<53:42,  5.85s/movie]



Downloading OMDb:  45%|████▍     | 449/1000 [04:23<53:42,  5.85s/movie]



Downloading OMDb:  45%|████▍     | 449/1000 [04:23<53:42,  5.85s/movie]




Downloading OMDb:  45%|████▍     | 449/1000 [04:23<53:42,  5.85s/movie]



Downloading OMDb:  45%|████▍     | 449/1000 [04:23<53:42,  5.85s/movie]



Downloading OMDb:  45%|████▍     | 449/1000 [04:23<53:42,  5.85s/movie]



Downloading OMDb:  45%|████▍     | 449/1000 [04:23<53:42,  5.85s/movie]

19:36:59 | ERROR | [tt0015873] OMDb error: Request limit reached!

19:36:59 | INFO | Worker 0: tt0016029

19:36:59 | ERROR | [tt0015841] OMDb error: Request limit reached!

19:36:59 | INFO | Worker 4: tt0016039

19:37:00 | ERROR | [tt0015881] OMDb error: Request limit reached!

19:37:00 | INFO | Worker 1: tt0016104

19:37:00 | ERROR | [tt0016004] OMDb error: Request limit reached!

Downloading OMDb:  45%|████▍     | 449/1000 [04:23<53:42,  5.85s/movie]



Downloading OMDb:  45%|████▍     | 449/1000 [04:23<53:42,  5.85s/movie]



Downloading OMDb:  45%|████▍     | 449/1000 [04:23<53:42,  5.85s/movie]



Downloading OMDb:  45%|████▍     | 449/1000 [04:23<53:42,  5.85s/movie]



Downloading OMDb:  45%|████▍     | 449/1000 [04:23<53:42,  5.85s/movie]



Downloading OMDb:  45%|████▍     | 449/1000 [04:23<53:42,  5.85s/movie]



Downloading OMDb:  45%|████▍     | 449/1000 [04:23<53:42,  5.85s/movie]

19:37:00 | INFO | Worker 2: tt0016123

19:37:00 | ERROR | [tt0016028] OMDb error: Request limit reached!

19:37:00 | INFO | Worker 3: tt0016220

19:37:00 | ERROR | [tt0016029] OMDb error: Request limit reached!

19:37:00 | INFO | Worker 0: tt0016230

19:37:00 | ERROR | [tt0016039] OMDb error: Request limit reached!

19:37:00 | INFO | Worker 4: tt0016332

Downloading OMDb:  45%|████▍     | 449/1000 [04:24<53:42,  5.85s/movie]




Downloading OMDb:  45%|████▍     | 449/1000 [04:24<53:42,  5.85s/movie]



Downloading OMDb:  45%|████▍     | 449/1000 [04:24<53:42,  5.85s/movie]



Downloading OMDb:  45%|████▍     | 449/1000 [04:24<53:42,  5.85s/movie]



Downloading OMDb:  45%|████▍     | 449/1000 [04:24<53:42,  5.85s/movie]



Downloading OMDb:  45%|████▍     | 449/1000 [04:24<53:42,  5.85s/movie]



Downloading OMDb:  45%|████▍     | 449/1000 [04:24<53:42,  5.85s/movie]




Downloading OMDb:  45%|████▍     | 449/1000 [04:24<53:42,  5.85s/movie]



Downloading OMDb:  45%|████▍     | 449/1000 [04:24<53:42,  5.85s/movie]



Downloading OMDb:  45%|████▍     | 449/1000 [04:24<53:42,  5.85s/movie]

19:37:00 | ERROR | [tt0016104] OMDb error: Request limit reached!

19:37:00 | INFO | Worker 1: tt0016394

19:37:00 | ERROR | [tt0016123] OMDb error: Request limit reached!

19:37:00 | INFO | Worker 2: tt0016473

19:37:00 | ERROR | [tt0016230] OMDb error: Request limit reached!

19:37:00 | INFO | Worker 0: tt0016481

19:37:00 | ERROR | [tt0016332] OMDb error: Request limit reached!

19:37:00 | INFO | Worker 4: tt0016544

19:37:00 | ERROR | [tt0016220] OMDb error: Request limit reached!

19:37:00 | INFO | Worker 3: tt0016627

Downloading OMDb:  45%|████▍     | 449/1000 [04:24<53:42,  5.85s/movie]



Downloading OMDb:  45%|████▍     | 449/1000 [04:24<53:42,  5.85s/movie]



Downloading OMDb:  45%|████▍     | 449/1000 [04:24<53:42,  5.85s/movie]




Downloading OMDb:  45%|████▍     | 449/1000 [04:24<53:42,  5.85s/movie]



Downloading OMDb:  45%|████▍     | 449/1000 [04:24<53:42,  5.85s/movie]



Downloading OMDb:  45%|████▍     | 449/1000 [04:24<53:42,  5.85s/movie]



Downloading OMDb:  45%|████▍     | 449/1000 [04:24<53:42,  5.85s/movie]



Downloading OMDb:  45%|████▍     | 449/1000 [04:24<53:42,  5.85s/movie]



Downloading OMDb:  45%|████▍     | 449/1000 [04:24<53:42,  5.85s/movie]




Downloading OMDb:  45%|████▍     | 449/1000 [04:24<53:42,  5.85s/movie]

19:37:00 | ERROR | [tt0016394] OMDb error: Request limit reached!

19:37:00 | INFO | Worker 1: tt0016629

19:37:00 | ERROR | [tt0016473] OMDb error: Request limit reached!

19:37:00 | INFO | Worker 2: tt0016630

19:37:00 | ERROR | [tt0016481] OMDb error: Request limit reached!

19:37:00 | INFO | Worker 0: tt0016641

19:37:00 | ERROR | [tt0016544] OMDb error: Request limit reached!

19:37:00 | INFO | Worker 4: tt0016654

19:37:00 | ERROR | [tt0016627] OMDb error: Request limit reached!

19:37:00 | INFO | Worker 3: tt0016669

Downloading OMDb:  45%|████▍     | 449/1000 [04:24<53:42,  5.85s/movie]



Downloading OMDb:  45%|████▍     | 449/1000 [04:24<53:42,  5.85s/movie]



Downloading OMDb:  45%|████▍     | 449/1000 [04:24<53:42,  5.85s/movie]



Downloading OMDb:  45%|████▍     | 449/1000 [04:24<53:42,  5.85s/movie]



Downloading OMDb:  45%|████▍     | 449/1000 [04:24<53:42,  5.85s/movie]




Downloading OMDb:  45%|████▍     | 449/1000 [04:24<53:42,  5.85s/movie]



Downloading OMDb:  45%|████▍     | 449/1000 [04:24<53:42,  5.85s/movie]



Downloading OMDb:  45%|████▍     | 449/1000 [04:24<53:42,  5.85s/movie]

19:37:00 | ERROR | [tt0016629] OMDb error: Request limit reached!

19:37:00 | INFO | Worker 1: tt0016690

19:37:00 | ERROR | [tt0016630] OMDb error: Request limit reached!

19:37:00 | INFO | Worker 2: tt0016804

19:37:00 | ERROR | [tt0016641] OMDb error: Request limit reached!

19:37:00 | INFO | Worker 0: tt0016822

19:37:00 | ERROR | [tt0016654] OMDb error: Request limit reached!

19:37:00 | INFO | Worker 4: tt0016847

Downloading OMDb:  45%|████▍     | 449/1000 [04:24<53:42,  5.85s/movie]



Downloading OMDb:  45%|████▍     | 449/1000 [04:24<53:42,  5.85s/movie]



Downloading OMDb:  45%|████▍     | 449/1000 [04:24<53:42,  5.85s/movie]




Downloading OMDb:  45%|████▍     | 449/1000 [04:24<53:42,  5.85s/movie]



Downloading OMDb:  45%|████▍     | 449/1000 [04:24<53:42,  5.85s/movie]



Downloading OMDb:  45%|████▍     | 449/1000 [04:24<53:42,  5.85s/movie]



Downloading OMDb:  45%|████▍     | 449/1000 [04:24<53:42,  5.85s/movie]



Downloading OMDb:  45%|████▍     | 449/1000 [04:24<53:42,  5.85s/movie]



Downloading OMDb:  45%|████▍     | 449/1000 [04:24<53:42,  5.85s/movie]




Downloading OMDb:  45%|████▍     | 449/1000 [04:24<53:42,  5.85s/movie]

19:37:01 | ERROR | [tt0016669] OMDb error: Request limit reached!

19:37:01 | INFO | Worker 3: tt0016884

19:37:01 | ERROR | [tt0016690] OMDb error: Request limit reached!

19:37:01 | INFO | Worker 1: tt0016895

19:37:01 | ERROR | [tt0016804] OMDb error: Request limit reached!

19:37:01 | INFO | Worker 2: tt0016953

19:37:01 | ERROR | [tt0016822] OMDb error: Request limit reached!

19:37:01 | INFO | Worker 0: tt0017048

19:37:01 | ERROR | [tt0016847] OMDb error: Request limit reached!

19:37:01 | INFO | Worker 4: tt0017075

Downloading OMDb:  45%|████▍     | 449/1000 [04:25<53:42,  5.85s/movie]



Downloading OMDb:  45%|████▍     | 449/1000 [04:25<53:42,  5.85s/movie]



Downloading OMDb:  45%|████▍     | 449/1000 [04:25<53:42,  5.85s/movie]



Downloading OMDb:  45%|████▍     | 449/1000 [04:25<53:42,  5.85s/movie]



Downloading OMDb:  45%|████▍     | 449/1000 [04:25<53:42,  5.85s/movie]




Downloading OMDb:  45%|████▍     | 449/1000 [04:25<53:42,  5.85s/movie]



Downloading OMDb:  45%|████▍     | 449/1000 [04:25<53:42,  5.85s/movie]



Downloading OMDb:  45%|████▍     | 449/1000 [04:25<53:42,  5.85s/movie]



Downloading OMDb:  45%|████▍     | 449/1000 [04:25<53:42,  5.85s/movie]



Downloading OMDb:  45%|████▍     | 449/1000 [04:25<53:42,  5.85s/movie]

19:37:01 | ERROR | [tt0016884] OMDb error: Request limit reached!

19:37:01 | INFO | Worker 3: tt0017128

19:37:01 | ERROR | [tt0016895] OMDb error: Request limit reached!

19:37:01 | INFO | Worker 1: tt0017136

19:37:01 | ERROR | [tt0016953] OMDb error: Request limit reached!

19:37:01 | INFO | Worker 2: tt0017196

19:37:01 | ERROR | [tt0017048] OMDb error: Request limit reached!

19:37:01 | INFO | Worker 0: tt0017271

19:37:01 | ERROR | [tt0017075] OMDb error: Request limit reached!

19:37:01 | INFO | Worker 4: tt0017350

Downloading OMDb:  45%|████▍     | 449/1000 [04:25<53:42,  5.85s/movie]




Downloading OMDb:  45%|████▍     | 449/1000 [04:25<53:42,  5.85s/movie]



Downloading OMDb:  45%|████▍     | 449/1000 [04:25<53:42,  5.85s/movie]



Downloading OMDb:  45%|████▍     | 449/1000 [04:25<53:42,  5.85s/movie]



Downloading OMDb:  45%|████▍     | 449/1000 [04:25<53:42,  5.85s/movie]



Downloading OMDb:  45%|████▍     | 449/1000 [04:25<53:42,  5.85s/movie]



Downloading OMDb:  45%|████▍     | 449/1000 [04:25<53:42,  5.85s/movie]



Downloading OMDb:  45%|████▍     | 449/1000 [04:25<53:42,  5.85s/movie]



Downloading OMDb:  45%|████▍     | 449/1000 [04:25<53:42,  5.85s/movie]




Downloading OMDb:  45%|████▍     | 449/1000 [04:25<53:42,  5.85s/movie]

19:37:01 | ERROR | [tt0017136] OMDb error: Request limit reached!

19:37:01 | INFO | Worker 1: tt0017416

19:37:01 | ERROR | [tt0017128] OMDb error: Request limit reached!

19:37:01 | INFO | Worker 3: tt0017423

19:37:01 | ERROR | [tt0017196] OMDb error: Request limit reached!

19:37:01 | INFO | Worker 2: tt0017437

19:37:01 | ERROR | [tt0017271] OMDb error: Request limit reached!

19:37:01 | INFO | Worker 0: tt0017448

19:37:01 | ERROR | [tt0017350] OMDb error: Request limit reached!

19:37:01 | INFO | Worker 4: tt0017449

Downloading OMDb:  45%|████▍     | 449/1000 [04:25<53:42,  5.85s/movie]



Downloading OMDb:  45%|████▍     | 449/1000 [04:25<53:42,  5.85s/movie]



Downloading OMDb:  45%|████▍     | 449/1000 [04:25<53:42,  5.85s/movie]



Downloading OMDb:  45%|████▍     | 449/1000 [04:25<53:42,  5.85s/movie]



Downloading OMDb:  45%|████▍     | 449/1000 [04:25<53:42,  5.85s/movie]




Downloading OMDb:  45%|████▍     | 449/1000 [04:25<53:42,  5.85s/movie]



Downloading OMDb:  45%|████▍     | 449/1000 [04:25<53:42,  5.85s/movie]



Downloading OMDb:  45%|████▍     | 449/1000 [04:25<53:42,  5.85s/movie]



Downloading OMDb:  45%|████▍     | 449/1000 [04:25<53:42,  5.85s/movie]



Downloading OMDb:  45%|████▍     | 449/1000 [04:25<53:42,  5.85s/movie]

19:37:01 | ERROR | [tt0017416] OMDb error: Request limit reached!

19:37:01 | INFO | Worker 1: tt0017463

19:37:01 | ERROR | [tt0017423] OMDb error: Request limit reached!

19:37:01 | INFO | Worker 3: tt0017534

19:37:01 | ERROR | [tt0017437] OMDb error: Request limit reached!

19:37:01 | INFO | Worker 2: tt0017567

19:37:01 | ERROR | [tt0017448] OMDb error: Request limit reached!

19:37:01 | INFO | Worker 0: tt0017668

19:37:02 | ERROR | [tt0017449] OMDb error: Request limit reached!

19:37:02 | INFO | Worker 4: tt0017739

Downloading OMDb:  45%|████▍     | 449/1000 [04:25<53:42,  5.85s/movie]




Downloading OMDb:  45%|████▍     | 449/1000 [04:25<53:42,  5.85s/movie]



Downloading OMDb:  45%|████▍     | 449/1000 [04:25<53:42,  5.85s/movie]



Downloading OMDb:  45%|████▍     | 449/1000 [04:25<53:42,  5.85s/movie]



Downloading OMDb:  45%|████▍     | 449/1000 [04:25<53:42,  5.85s/movie]



Downloading OMDb:  45%|████▍     | 449/1000 [04:25<53:42,  5.85s/movie]



Downloading OMDb:  45%|████▍     | 449/1000 [04:25<53:42,  5.85s/movie]



Downloading OMDb:  45%|████▍     | 449/1000 [04:25<53:42,  5.85s/movie]



Downloading OMDb:  45%|████▍     | 449/1000 [04:25<53:42,  5.85s/movie]




Downloading OMDb:  45%|████▍     | 449/1000 [04:25<53:42,  5.85s/movie]

19:37:02 | ERROR | [tt0017463] OMDb error: Request limit reached!

19:37:02 | INFO | Worker 1: tt0017743

19:37:02 | ERROR | [tt0017534] OMDb error: Request limit reached!

19:37:02 | INFO | Worker 3: tt0017765

19:37:02 | ERROR | [tt0017567] OMDb error: Request limit reached!

19:37:02 | INFO | Worker 2: tt0017825

19:37:02 | ERROR | [tt0017668] OMDb error: Request limit reached!

19:37:02 | INFO | Worker 0: tt0017843

19:37:02 | ERROR | [tt0017739] OMDb error: Request limit reached!

19:37:02 | INFO | Worker 4: tt0017925

Downloading OMDb:  45%|████▍     | 449/1000 [04:26<53:42,  5.85s/movie]



Downloading OMDb:  45%|████▍     | 449/1000 [04:26<53:42,  5.85s/movie]



Downloading OMDb:  45%|████▍     | 449/1000 [04:26<53:42,  5.85s/movie]



Downloading OMDb:  45%|████▍     | 449/1000 [04:26<53:42,  5.85s/movie]



Downloading OMDb:  45%|████▍     | 449/1000 [04:26<53:42,  5.85s/movie]




Downloading OMDb:  45%|████▍     | 449/1000 [04:26<53:42,  5.85s/movie]



Downloading OMDb:  45%|████▍     | 449/1000 [04:26<53:42,  5.85s/movie]



Downloading OMDb:  45%|████▍     | 449/1000 [04:26<53:42,  5.85s/movie]



Downloading OMDb:  45%|████▍     | 449/1000 [04:26<53:42,  5.85s/movie]



Downloading OMDb:  45%|████▍     | 449/1000 [04:26<53:42,  5.85s/movie]

19:37:02 | ERROR | [tt0017743] OMDb error: Request limit reached!

19:37:02 | INFO | Worker 1: tt0017961

19:37:02 | ERROR | [tt0017765] OMDb error: Request limit reached!

19:37:02 | INFO | Worker 3: tt0018033

19:37:02 | ERROR | [tt0017825] OMDb error: Request limit reached!

19:37:02 | INFO | Worker 2: tt0018037

19:37:02 | ERROR | [tt0017843] OMDb error: Request limit reached!

19:37:02 | INFO | Worker 0: tt0018051

19:37:02 | ERROR | [tt0017925] OMDb error: Request limit reached!

19:37:02 | INFO | Worker 4: tt0018054

Downloading OMDb:  45%|████▍     | 449/1000 [04:26<53:42,  5.85s/movie]




Downloading OMDb:  45%|████▍     | 449/1000 [04:26<53:42,  5.85s/movie]

19:37:02 | ERROR | [tt0017961] OMDb error: Request limit reached!

19:37:02 | INFO | Worker 1: tt0018066

CancelledError:

Downloading OMDb:  45%|████▍     | 449/1000 [04:26<53:42,  5.85s/movie]



Downloading OMDb:  45%|████▍     | 449/1000 [04:26<53:42,  5.85s/movie]



Downloading OMDb:  45%|████▍     | 449/1000 [04:26<53:42,  5.85s/movie]



Downloading OMDb:  45%|████▍     | 449/1000 [04:26<53:42,  5.85s/movie]



Downloading OMDb:  45%|████▍     | 449/1000 [04:26<53:42,  5.85s/movie]

19:37:02 | ERROR | [tt0018051] Unexpected error: Connector is closed. — retrying in 2s

19:37:02 | ERROR | [tt0018037] Unexpected error: Connector is closed. — retrying in 2s

19:37:02 | ERROR | [tt0018033] Unexpected error: Connector is closed. — retrying in 2s

19:37:02 | ERROR | [tt0018066] Unexpected error: Connector is closed. — retrying in 2s

19:37:02 | ERROR | [tt0018054] Unexpected error: Connector is closed. — retrying in 2s

Downloading OMDb:  45%|████▍     | 449/1000 [04:28<53:42,  5.85s/movie]



Downloading OMDb:  45%|████▍     | 449/1000 [04:28<53:42,  5.85s/movie]



Downloading OMDb:  45%|████▍     | 449/1000 [04:28<53:42,  5.85s/movie]



Downloading OMDb:  45%|████▍     | 449/1000 [04:28<53:42,  5.85s/movie]



Downloading OMDb:  45%|████▍     | 449/1000 [04:28<53:42,  5.85s/movie]

19:37:04 | ERROR | [tt0018051] Unexpected error: Session is closed — retrying in 4s

19:37:04 | ERROR | [tt0018037] Unexpected error: Session is closed — retrying in 4s

19:37:04 | ERROR | [tt0018033] Unexpected error: Session is closed — retrying in 4s

19:37:04 | ERROR | [tt0018066] Unexpected error: Session is closed — retrying in 4s

19:37:04 | ERROR | [tt0018054] Unexpected error: Session is closed — retrying in 4s

Downloading OMDb:  45%|████▍     | 449/1000 [04:32<53:42,  5.85s/movie]



Downloading OMDb:  45%|████▍     | 449/1000 [04:32<53:42,  5.85s/movie]



Downloading OMDb:  45%|████▍     | 449/1000 [04:32<53:42,  5.85s/movie]



Downloading OMDb:  45%|████▍     | 449/1000 [04:32<53:42,  5.85s/movie]



Downloading OMDb:  45%|████▍     | 449/1000 [04:32<53:42,  5.85s/movie]

19:37:08 | ERROR | [tt0018051] Unexpected error: Session is closed — retrying in 6s

19:37:08 | ERROR | [tt0018037] Unexpected error: Session is closed — retrying in 6s

19:37:08 | ERROR | [tt0018033] Unexpected error: Session is closed — retrying in 6s

19:37:08 | ERROR | [tt0018066] Unexpected error: Session is closed — retrying in 6s

19:37:08 | ERROR | [tt0018054] Unexpected error: Session is closed — retrying in 6s

Downloading OMDb:  45%|████▍     | 449/1000 [04:38<53:42,  5.85s/movie]



Downloading OMDb:  45%|████▍     | 449/1000 [04:38<53:42,  5.85s/movie]



Downloading OMDb:  45%|████▍     | 449/1000 [04:38<53:42,  5.85s/movie]



Downloading OMDb:  45%|████▍     | 449/1000 [04:38<53:42,  5.85s/movie]



Downloading OMDb:  45%|████▍     | 449/1000 [04:38<53:42,  5.85s/movie]

19:37:14 | ERROR | [tt0018051] Unexpected error: Session is closed — retrying in 8s

19:37:14 | ERROR | [tt0018037] Unexpected error: Session is closed — retrying in 8s

19:37:14 | ERROR | [tt0018033] Unexpected error: Session is closed — retrying in 8s

19:37:14 | ERROR | [tt0018066] Unexpected error: Session is closed — retrying in 8s

19:37:14 | ERROR | [tt0018054] Unexpected error: Session is closed — retrying in 8s

Downloading OMDb:  45%|████▍     | 449/1000 [04:46<53:42,  5.85s/movie]



Downloading OMDb:  45%|████▍     | 449/1000 [04:46<53:42,  5.85s/movie]



Downloading OMDb:  45%|████▍     | 449/1000 [04:46<53:42,  5.85s/movie]



Downloading OMDb:  45%|████▍     | 449/1000 [04:46<53:42,  5.85s/movie]



Downloading OMDb:  45%|████▍     | 449/1000 [04:46<53:42,  5.85s/movie]

19:37:22 | ERROR | [tt0018051] Unexpected error: Session is closed — retrying in 10s

19:37:22 | ERROR | [tt0018037] Unexpected error: Session is closed — retrying in 10s

19:37:22 | ERROR | [tt0018033] Unexpected error: Session is closed — retrying in 10s

19:37:22 | ERROR | [tt0018066] Unexpected error: Session is closed — retrying in 10s

19:37:22 | ERROR | [tt0018054] Unexpected error: Session is closed — retrying in 10s

Downloading OMDb:  45%|████▌     | 454/1000 [04:56<53:40,  5.90s/movie]




Downloading OMDb:  45%|████▌     | 454/1000 [04:56<53:40,  5.90s/movie]



Downloading OMDb:  45%|████▌     | 454/1000 [04:56<53:40,  5.90s/movie]



Downloading OMDb:  45%|████▌     | 454/1000 [04:56<53:40,  5.90s/movie]



Downloading OMDb:  45%|████▌     | 454/1000 [04:56<53:40,  5.90s/movie]



Downloading OMDb:  45%|████▌     | 454/1000 [04:56<53:40,  5.90s/movie]



Downloading OMDb:  45%|████▌     | 454/1000 [04:56<53:40,  5.90s/movie]



Downloading OMDb:  45%|████▌     | 454/1000 [04:56<53:40,  5.90s/movie]



Downloading OMDb:  45%|████▌     | 454/1000 [04:56<53:40,  5.90s/movie]



Downloading OMDb:  45%|████▌     | 454/1000 [04:56<53:40,  5.90s/movie]



Downloading OMDb:  45%|████▌     | 454/1000 [04:56<53:40,  5.90s/movie]



Downloading OMDb:  45%|████▌     | 454/1000 [04:56<53:40,  5.90s/movie]



Downloading OMDb:  45%|████▌     | 454/1000 [04:56<53:40,  5.90s/movie]



Downloading OMDb:  45%|████▌     | 454/1000 [04:56<53:40,  5.90s/movie]



Downloading OMDb:  45%|████▌     | 454/1000 [04:56<53:40,  5.90s/movie]

19:37:32 | CRITICAL | [tt0018051] FAILED permanently after 5 retries

19:37:32 | INFO | Worker 0: tt0018097

19:37:32 | ERROR | [tt0018097] Unexpected error: Session is closed — retrying in 2s

19:37:32 | CRITICAL | [tt0018037] FAILED permanently after 5 retries

19:37:32 | INFO | Worker 2: tt0018107

19:37:32 | ERROR | [tt0018107] Unexpected error: Session is closed — retrying in 2s

19:37:32 | CRITICAL | [tt0018033] FAILED permanently after 5 retries

19:37:32 | INFO | Worker 3: tt0018183

19:37:32 | ERROR | [tt0018183] Unexpected error: Session is closed — retrying in 2s

19:37:32 | CRITICAL | [tt0018066] FAILED permanently after 5 retries

19:37:32 | INFO | Worker 1: tt0018192

19:37:32 | ERROR | [tt0018192] Unexpected error: Session is closed — retrying in 2s

19:37:32 | CRITICAL | [tt0018054] FAILED permanently after 5 retries

19:37:32 | INFO | Worker 4: tt0018217

19:37:32 | ERROR | [tt0018217] Unexpected error: Session is closed — retrying in 2s

Downloading OMDb:  45%|████▌     | 454/1000 [04:58<53:40,  5.90s/movie]



Downloading OMDb:  45%|████▌     | 454/1000 [04:58<53:40,  5.90s/movie]



Downloading OMDb:  45%|████▌     | 454/1000 [04:58<53:40,  5.90s/movie]



Downloading OMDb:  45%|████▌     | 454/1000 [04:58<53:40,  5.90s/movie]



Downloading OMDb:  45%|████▌     | 454/1000 [04:58<53:40,  5.90s/movie]

19:37:34 | ERROR | [tt0018097] Unexpected error: Session is closed — retrying in 4s

19:37:34 | ERROR | [tt0018107] Unexpected error: Session is closed — retrying in 4s

19:37:34 | ERROR | [tt0018183] Unexpected error: Session is closed — retrying in 4s

19:37:34 | ERROR | [tt0018192] Unexpected error: Session is closed — retrying in 4s

19:37:34 | ERROR | [tt0018217] Unexpected error: Session is closed — retrying in 4s

Downloading OMDb:  45%|████▌     | 454/1000 [05:02<53:40,  5.90s/movie]



Downloading OMDb:  45%|████▌     | 454/1000 [05:02<53:40,  5.90s/movie]



Downloading OMDb:  45%|████▌     | 454/1000 [05:02<53:40,  5.90s/movie]



Downloading OMDb:  45%|████▌     | 454/1000 [05:02<53:40,  5.90s/movie]



Downloading OMDb:  45%|████▌     | 454/1000 [05:02<53:40,  5.90s/movie]

19:37:38 | ERROR | [tt0018097] Unexpected error: Session is closed — retrying in 6s

19:37:38 | ERROR | [tt0018107] Unexpected error: Session is closed — retrying in 6s

19:37:38 | ERROR | [tt0018183] Unexpected error: Session is closed — retrying in 6s

19:37:38 | ERROR | [tt0018192] Unexpected error: Session is closed — retrying in 6s

19:37:38 | ERROR | [tt0018217] Unexpected error: Session is closed — retrying in 6s

Downloading OMDb:  45%|████▌     | 454/1000 [05:08<53:40,  5.90s/movie]



Downloading OMDb:  45%|████▌     | 454/1000 [05:08<53:40,  5.90s/movie]



Downloading OMDb:  45%|████▌     | 454/1000 [05:08<53:40,  5.90s/movie]



Downloading OMDb:  45%|████▌     | 454/1000 [05:08<53:40,  5.90s/movie]



Downloading OMDb:  45%|████▌     | 454/1000 [05:08<53:40,  5.90s/movie]

19:37:44 | ERROR | [tt0018097] Unexpected error: Session is closed — retrying in 8s

19:37:44 | ERROR | [tt0018107] Unexpected error: Session is closed — retrying in 8s

19:37:44 | ERROR | [tt0018183] Unexpected error: Session is closed — retrying in 8s

19:37:45 | ERROR | [tt0018192] Unexpected error: Session is closed — retrying in 8s

19:37:45 | ERROR | [tt0018217] Unexpected error: Session is closed — retrying in 8s

Downloading OMDb:  45%|████▌     | 454/1000 [05:16<53:40,  5.90s/movie]



Downloading OMDb:  45%|████▌     | 454/1000 [05:16<53:40,  5.90s/movie]



Downloading OMDb:  45%|████▌     | 454/1000 [05:16<53:40,  5.90s/movie]



Downloading OMDb:  45%|████▌     | 454/1000 [05:16<53:40,  5.90s/movie]



Downloading OMDb:  45%|████▌     | 454/1000 [05:16<53:40,  5.90s/movie]

19:37:52 | ERROR | [tt0018097] Unexpected error: Session is closed — retrying in 10s

19:37:53 | ERROR | [tt0018107] Unexpected error: Session is closed — retrying in 10s

19:37:53 | ERROR | [tt0018183] Unexpected error: Session is closed — retrying in 10s

19:37:53 | ERROR | [tt0018192] Unexpected error: Session is closed — retrying in 10s

19:37:53 | ERROR | [tt0018217] Unexpected error: Session is closed — retrying in 10s

Downloading OMDb:  46%|████▌     | 459/1000 [05:26<53:30,  5.93s/movie]




Downloading OMDb:  46%|████▌     | 459/1000 [05:26<53:30,  5.93s/movie]



Downloading OMDb:  46%|████▌     | 459/1000 [05:26<53:30,  5.93s/movie]



Downloading OMDb:  46%|████▌     | 459/1000 [05:26<53:30,  5.93s/movie]



Downloading OMDb:  46%|████▌     | 459/1000 [05:26<53:30,  5.93s/movie]



Downloading OMDb:  46%|████▌     | 459/1000 [05:26<53:30,  5.93s/movie]



Downloading OMDb:  46%|████▌     | 459/1000 [05:26<53:30,  5.93s/movie]



Downloading OMDb:  46%|████▌     | 459/1000 [05:26<53:30,  5.93s/movie]



Downloading OMDb:  46%|████▌     | 459/1000 [05:26<53:30,  5.93s/movie]



Downloading OMDb:  46%|████▌     | 459/1000 [05:26<53:30,  5.93s/movie]



Downloading OMDb:  46%|████▌     | 459/1000 [05:26<53:30,  5.93s/movie]



Downloading OMDb:  46%|████▌     | 459/1000 [05:26<53:30,  5.93s/movie]



Downloading OMDb:  46%|████▌     | 459/1000 [05:26<53:30,  5.93s/movie]



Downloading OMDb:  46%|████▌     | 459/1000 [05:26<53:30,  5.93s/movie]



Downloading OMDb:  46%|████▌     | 459/1000 [05:26<53:30,  5.93s/movie]

19:38:03 | CRITICAL | [tt0018097] FAILED permanently after 5 retries

19:38:03 | INFO | Worker 0: tt0018311

19:38:03 | ERROR | [tt0018311] Unexpected error: Session is closed — retrying in 2s

19:38:03 | CRITICAL | [tt0018107] FAILED permanently after 5 retries

19:38:03 | INFO | Worker 2: tt0018328

19:38:03 | ERROR | [tt0018328] Unexpected error: Session is closed — retrying in 2s

19:38:03 | CRITICAL | [tt0018183] FAILED permanently after 5 retries

19:38:03 | INFO | Worker 3: tt0018379

19:38:03 | ERROR | [tt0018379] Unexpected error: Session is closed — retrying in 2s

19:38:03 | CRITICAL | [tt0018192] FAILED permanently after 5 retries

19:38:03 | INFO | Worker 1: tt0018440

19:38:03 | ERROR | [tt0018440] Unexpected error: Session is closed — retrying in 2s

19:38:03 | CRITICAL | [tt0018217] FAILED permanently after 5 retries

19:38:03 | INFO | Worker 4: tt0018451

19:38:03 | ERROR | [tt0018451] Unexpected error: Session is closed — retrying in 2s

Downloading OMDb:  46%|████▌     | 459/1000 [05:28<53:30,  5.93s/movie]



Downloading OMDb:  46%|████▌     | 459/1000 [05:28<53:30,  5.93s/movie]



Downloading OMDb:  46%|████▌     | 459/1000 [05:28<53:30,  5.93s/movie]



Downloading OMDb:  46%|████▌     | 459/1000 [05:28<53:30,  5.93s/movie]



Downloading OMDb:  46%|████▌     | 459/1000 [05:28<53:30,  5.93s/movie]

19:38:05 | ERROR | [tt0018311] Unexpected error: Session is closed — retrying in 4s

19:38:05 | ERROR | [tt0018328] Unexpected error: Session is closed — retrying in 4s

19:38:05 | ERROR | [tt0018379] Unexpected error: Session is closed — retrying in 4s

19:38:05 | ERROR | [tt0018440] Unexpected error: Session is closed — retrying in 4s

19:38:05 | ERROR | [tt0018451] Unexpected error: Session is closed — retrying in 4s

Downloading OMDb:  46%|████▌     | 459/1000 [05:32<53:30,  5.93s/movie]



Downloading OMDb:  46%|████▌     | 459/1000 [05:32<53:30,  5.93s/movie]



Downloading OMDb:  46%|████▌     | 459/1000 [05:32<53:30,  5.93s/movie]



Downloading OMDb:  46%|████▌     | 459/1000 [05:32<53:30,  5.93s/movie]



Downloading OMDb:  46%|████▌     | 459/1000 [05:32<53:30,  5.93s/movie]

19:38:09 | ERROR | [tt0018311] Unexpected error: Session is closed — retrying in 6s

19:38:09 | ERROR | [tt0018328] Unexpected error: Session is closed — retrying in 6s

19:38:09 | ERROR | [tt0018379] Unexpected error: Session is closed — retrying in 6s

19:38:09 | ERROR | [tt0018440] Unexpected error: Session is closed — retrying in 6s

19:38:09 | ERROR | [tt0018451] Unexpected error: Session is closed — retrying in 6s

Downloading OMDb:  46%|████▌     | 459/1000 [05:38<53:30,  5.93s/movie]



Downloading OMDb:  46%|████▌     | 459/1000 [05:38<53:30,  5.93s/movie]



Downloading OMDb:  46%|████▌     | 459/1000 [05:38<53:30,  5.93s/movie]



Downloading OMDb:  46%|████▌     | 459/1000 [05:38<53:30,  5.93s/movie]



Downloading OMDb:  46%|████▌     | 459/1000 [05:38<53:30,  5.93s/movie]

19:38:15 | ERROR | [tt0018311] Unexpected error: Session is closed — retrying in 8s

19:38:15 | ERROR | [tt0018328] Unexpected error: Session is closed — retrying in 8s

19:38:15 | ERROR | [tt0018379] Unexpected error: Session is closed — retrying in 8s

19:38:15 | ERROR | [tt0018440] Unexpected error: Session is closed — retrying in 8s

19:38:15 | ERROR | [tt0018451] Unexpected error: Session is closed — retrying in 8s

Downloading OMDb:  46%|████▌     | 459/1000 [05:46<53:30,  5.93s/movie]



Downloading OMDb:  46%|████▌     | 459/1000 [05:46<53:30,  5.93s/movie]



Downloading OMDb:  46%|████▌     | 459/1000 [05:46<53:30,  5.93s/movie]



Downloading OMDb:  46%|████▌     | 459/1000 [05:46<53:30,  5.93s/movie]



Downloading OMDb:  46%|████▌     | 459/1000 [05:46<53:30,  5.93s/movie]

19:38:23 | ERROR | [tt0018311] Unexpected error: Session is closed — retrying in 10s

19:38:23 | ERROR | [tt0018328] Unexpected error: Session is closed — retrying in 10s

19:38:23 | ERROR | [tt0018379] Unexpected error: Session is closed — retrying in 10s

19:38:23 | ERROR | [tt0018440] Unexpected error: Session is closed — retrying in 10s

19:38:23 | ERROR | [tt0018451] Unexpected error: Session is closed — retrying in 10s

Downloading OMDb:  46%|████▋     | 464/1000 [05:56<53:13,  5.96s/movie]




Downloading OMDb:  46%|████▋     | 464/1000 [05:56<53:13,  5.96s/movie]



Downloading OMDb:  46%|████▋     | 464/1000 [05:56<53:13,  5.96s/movie]



Downloading OMDb:  46%|████▋     | 464/1000 [05:56<53:13,  5.96s/movie]



Downloading OMDb:  46%|████▋     | 464/1000 [05:56<53:13,  5.96s/movie]



Downloading OMDb:  46%|████▋     | 464/1000 [05:56<53:13,  5.96s/movie]



Downloading OMDb:  46%|████▋     | 464/1000 [05:56<53:13,  5.96s/movie]



Downloading OMDb:  46%|████▋     | 464/1000 [05:56<53:13,  5.96s/movie]



Downloading OMDb:  46%|████▋     | 464/1000 [05:56<53:13,  5.96s/movie]



Downloading OMDb:  46%|████▋     | 464/1000 [05:56<53:13,  5.96s/movie]



Downloading OMDb:  46%|████▋     | 464/1000 [05:56<53:13,  5.96s/movie]



Downloading OMDb:  46%|████▋     | 464/1000 [05:56<53:13,  5.96s/movie]



Downloading OMDb:  46%|████▋     | 464/1000 [05:56<53:13,  5.96s/movie]



Downloading OMDb:  46%|████▋     | 464/1000 [05:56<53:13,  5.96s/movie]



Downloading OMDb:  46%|████▋     | 464/1000 [05:56<53:13,  5.96s/movie]

19:38:33 | CRITICAL | [tt0018311] FAILED permanently after 5 retries

19:38:33 | INFO | Worker 0: tt0018455

19:38:33 | ERROR | [tt0018455] Unexpected error: Session is closed — retrying in 2s

19:38:33 | CRITICAL | [tt0018328] FAILED permanently after 5 retries

19:38:33 | INFO | Worker 2: tt0018471

19:38:33 | ERROR | [tt0018471] Unexpected error: Session is closed — retrying in 2s

19:38:33 | CRITICAL | [tt0018379] FAILED permanently after 5 retries

19:38:33 | INFO | Worker 3: tt0018505

19:38:33 | ERROR | [tt0018505] Unexpected error: Session is closed — retrying in 2s

19:38:33 | CRITICAL | [tt0018440] FAILED permanently after 5 retries

19:38:33 | INFO | Worker 1: tt0018515

19:38:33 | ERROR | [tt0018515] Unexpected error: Session is closed — retrying in 2s

19:38:33 | CRITICAL | [tt0018451] FAILED permanently after 5 retries

19:38:33 | INFO | Worker 4: tt0018523

19:38:33 | ERROR | [tt0018523] Unexpected error: Session is closed — retrying in 2s

Downloading OMDb:  46%|████▋     | 464/1000 [05:58<53:13,  5.96s/movie]



Downloading OMDb:  46%|████▋     | 464/1000 [05:58<53:13,  5.96s/movie]



Downloading OMDb:  46%|████▋     | 464/1000 [05:58<53:13,  5.96s/movie]



Downloading OMDb:  46%|████▋     | 464/1000 [05:58<53:13,  5.96s/movie]



Downloading OMDb:  46%|████▋     | 464/1000 [05:58<53:13,  5.96s/movie]

19:38:35 | ERROR | [tt0018455] Unexpected error: Session is closed — retrying in 4s

19:38:35 | ERROR | [tt0018471] Unexpected error: Session is closed — retrying in 4s

19:38:35 | ERROR | [tt0018505] Unexpected error: Session is closed — retrying in 4s

19:38:35 | ERROR | [tt0018515] Unexpected error: Session is closed — retrying in 4s

19:38:35 | ERROR | [tt0018523] Unexpected error: Session is closed — retrying in 4s

Downloading OMDb:  46%|████▋     | 464/1000 [06:02<53:13,  5.96s/movie]



Downloading OMDb:  46%|████▋     | 464/1000 [06:02<53:13,  5.96s/movie]



Downloading OMDb:  46%|████▋     | 464/1000 [06:02<53:13,  5.96s/movie]



Downloading OMDb:  46%|████▋     | 464/1000 [06:02<53:13,  5.96s/movie]



Downloading OMDb:  46%|████▋     | 464/1000 [06:02<53:13,  5.96s/movie]

19:38:39 | ERROR | [tt0018455] Unexpected error: Session is closed — retrying in 6s

19:38:39 | ERROR | [tt0018471] Unexpected error: Session is closed — retrying in 6s

19:38:39 | ERROR | [tt0018505] Unexpected error: Session is closed — retrying in 6s

19:38:39 | ERROR | [tt0018515] Unexpected error: Session is closed — retrying in 6s

19:38:39 | ERROR | [tt0018523] Unexpected error: Session is closed — retrying in 6s

Downloading OMDb:  46%|████▋     | 464/1000 [06:08<53:13,  5.96s/movie]



Downloading OMDb:  46%|████▋     | 464/1000 [06:08<53:13,  5.96s/movie]



Downloading OMDb:  46%|████▋     | 464/1000 [06:08<53:13,  5.96s/movie]



Downloading OMDb:  46%|████▋     | 464/1000 [06:08<53:13,  5.96s/movie]



Downloading OMDb:  46%|████▋     | 464/1000 [06:08<53:13,  5.96s/movie]

19:38:45 | ERROR | [tt0018455] Unexpected error: Session is closed — retrying in 8s

19:38:45 | ERROR | [tt0018471] Unexpected error: Session is closed — retrying in 8s

19:38:45 | ERROR | [tt0018505] Unexpected error: Session is closed — retrying in 8s

19:38:45 | ERROR | [tt0018515] Unexpected error: Session is closed — retrying in 8s

19:38:45 | ERROR | [tt0018523] Unexpected error: Session is closed — retrying in 8s

Downloading OMDb:  46%|████▋     | 464/1000 [06:16<53:13,  5.96s/movie]



Downloading OMDb:  46%|████▋     | 464/1000 [06:16<53:13,  5.96s/movie]



Downloading OMDb:  46%|████▋     | 464/1000 [06:16<53:13,  5.96s/movie]



Downloading OMDb:  46%|████▋     | 464/1000 [06:16<53:13,  5.96s/movie]



Downloading OMDb:  46%|████▋     | 464/1000 [06:16<53:13,  5.96s/movie]

19:38:53 | ERROR | [tt0018455] Unexpected error: Session is closed — retrying in 10s

19:38:53 | ERROR | [tt0018471] Unexpected error: Session is closed — retrying in 10s

19:38:53 | ERROR | [tt0018505] Unexpected error: Session is closed — retrying in 10s

19:38:53 | ERROR | [tt0018515] Unexpected error: Session is closed — retrying in 10s

19:38:53 | ERROR | [tt0018523] Unexpected error: Session is closed — retrying in 10s

Downloading OMDb:  47%|████▋     | 469/1000 [06:26<52:53,  5.98s/movie]




Downloading OMDb:  47%|████▋     | 469/1000 [06:26<52:53,  5.98s/movie]



Downloading OMDb:  47%|████▋     | 469/1000 [06:26<52:53,  5.98s/movie]



Downloading OMDb:  47%|████▋     | 469/1000 [06:26<52:53,  5.98s/movie]



Downloading OMDb:  47%|████▋     | 469/1000 [06:26<52:53,  5.98s/movie]



Downloading OMDb:  47%|████▋     | 469/1000 [06:26<52:53,  5.98s/movie]



Downloading OMDb:  47%|████▋     | 469/1000 [06:26<52:53,  5.98s/movie]



Downloading OMDb:  47%|████▋     | 469/1000 [06:26<52:53,  5.98s/movie]



Downloading OMDb:  47%|████▋     | 469/1000 [06:26<52:53,  5.98s/movie]



Downloading OMDb:  47%|████▋     | 469/1000 [06:26<52:53,  5.98s/movie]



Downloading OMDb:  47%|████▋     | 469/1000 [06:26<52:53,  5.98s/movie]



Downloading OMDb:  47%|████▋     | 469/1000 [06:26<52:53,  5.98s/movie]



Downloading OMDb:  47%|████▋     | 469/1000 [06:26<52:53,  5.98s/movie]




Downloading OMDb:  47%|████▋     | 469/1000 [06:26<52:53,  5.98s/movie]



Downloading OMDb:  47%|████▋     | 469/1000 [06:26<52:53,  5.98s/movie]

19:39:03 | CRITICAL | [tt0018455] FAILED permanently after 5 retries

19:39:03 | INFO | Worker 0: tt0018526

19:39:03 | ERROR | [tt0018526] Unexpected error: Session is closed — retrying in 2s

19:39:03 | CRITICAL | [tt0018471] FAILED permanently after 5 retries

19:39:03 | INFO | Worker 2: tt0018528

19:39:03 | ERROR | [tt0018528] Unexpected error: Session is closed — retrying in 2s

19:39:03 | CRITICAL | [tt0018505] FAILED permanently after 5 retries

19:39:03 | INFO | Worker 3: tt0018578

19:39:03 | ERROR | [tt0018578] Unexpected error: Session is closed — retrying in 2s

19:39:03 | CRITICAL | [tt0018515] FAILED permanently after 5 retries

19:39:03 | INFO | Worker 1: tt0018618

19:39:03 | ERROR | [tt0018618] Unexpected error: Session is closed — retrying in 2s

19:39:03 | CRITICAL | [tt0018523] FAILED permanently after 5 retries

19:39:03 | INFO | Worker 4: tt0018684

19:39:03 | ERROR | [tt0018684] Unexpected error: Session is closed — retrying in 2s

Downloading OMDb:  47%|████▋     | 469/1000 [06:28<52:53,  5.98s/movie]



Downloading OMDb:  47%|████▋     | 469/1000 [06:28<52:53,  5.98s/movie]



Downloading OMDb:  47%|████▋     | 469/1000 [06:28<52:53,  5.98s/movie]



Downloading OMDb:  47%|████▋     | 469/1000 [06:28<52:53,  5.98s/movie]



Downloading OMDb:  47%|████▋     | 469/1000 [06:28<52:53,  5.98s/movie]

19:39:05 | ERROR | [tt0018526] Unexpected error: Session is closed — retrying in 4s

19:39:05 | ERROR | [tt0018528] Unexpected error: Session is closed — retrying in 4s

19:39:05 | ERROR | [tt0018578] Unexpected error: Session is closed — retrying in 4s

19:39:05 | ERROR | [tt0018618] Unexpected error: Session is closed — retrying in 4s

19:39:05 | ERROR | [tt0018684] Unexpected error: Session is closed — retrying in 4s

Downloading OMDb:  47%|████▋     | 469/1000 [06:32<52:53,  5.98s/movie]



Downloading OMDb:  47%|████▋     | 469/1000 [06:32<52:53,  5.98s/movie]



Downloading OMDb:  47%|████▋     | 469/1000 [06:32<52:53,  5.98s/movie]



Downloading OMDb:  47%|████▋     | 469/1000 [06:32<52:53,  5.98s/movie]



Downloading OMDb:  47%|████▋     | 469/1000 [06:32<52:53,  5.98s/movie]

19:39:09 | ERROR | [tt0018526] Unexpected error: Session is closed — retrying in 6s

19:39:09 | ERROR | [tt0018528] Unexpected error: Session is closed — retrying in 6s

19:39:09 | ERROR | [tt0018578] Unexpected error: Session is closed — retrying in 6s

19:39:09 | ERROR | [tt0018618] Unexpected error: Session is closed — retrying in 6s

19:39:09 | ERROR | [tt0018684] Unexpected error: Session is closed — retrying in 6s